#+OPTIONS: toc:nil
#+LATEX_HEADER: \setcounter{secnumdepth}{0}

* Search for solar axions using a 7-GridPix IAXO prototype detector at CAST

The Standard Model of particle physics describes three out of four
known fundamental forces of nature very successfully. However, open
questions remain. One of these, the 'strong CP problem', asks why the
neutron has no electric dipole moment. This 'mathematical' problem can
be neatly solved by the introduction of a new hypothetical particle,
the /axion/. This particle can feebly interact with photons and
leptons. Axions can be produced in the core of the Sun at very high
rates. Once produced they escape the Sun. On Earth we can try to
detect them using strong magnetic fields. The latest such experiment
is the CERN Axion Solar Telescope (CAST). Axions carry the energy of
the photons which produced them, placing them in the soft X-ray energy
range.

In this thesis, a gaseous detector containing 7-GridPixes was deployed
at the CAST experiment in 2017/18 to follow up on measurements with a
single GridPix detector in 2014/15. $\SI{3150}{h}$ of background and
$\SI{160}{h}$ of solar tracking data was taken. Such data is dominated
by cosmic radiation, radioactive background and X-ray
fluorescence. Methods to suppress this background and extract the few
possible axion signals are needed. A software library
~TimepixAnalysis~ was developed during this thesis to reconstruct and
analyze the CAST data.

Classification of events into background- or signal-like (X-ray) data,
uses a machine learning approach. A multilayer perceptron (type of
artificial neural network) was trained on synthetic X-rays and
background data of 6 of the 7 chips (without the axion sensitive
chip). Significant improvements to signal efficiency at comparable
background rates are achieved, compared to the method used for the old
detector.

As the solar tracking data showed no signal excess, a limit
calculation method was developed. It builds on the unbinned Bayesian
likelihood method used in the 2017 CAST Nature paper. It is extended
to allow the inclusion of systematic uncertainties as nuisance
parameters. Due to the expensive evaluation of such a likelihood
function, a Markov Chain Monte Carlo approach is used.

The limit calculation requires the 'axion image' produced by the
Lawrence Livermore National Laboratory telescope at CAST. To
characterize this, a raytracing simulation taking into account the
axion production rates in the Sun and reflection through the X-ray
optic was developed. It was verified against PANTER measurements of
the telescope.

With the software and detector advances, world best limits could be
set on the axion-electron and the chameleon coupling (another
hypothetical particle). The previous best limit on the axion-electron
coupling is improved from $g_{ae}·g_{aγ} \lesssim \SI{8.1e-23}{GeV⁻¹}$
to $g_{ae}·g_{aγ} \lesssim \SI{7.35e-23}{GeV⁻¹}$ and the chameleon
coupling from $β_γ < \num{5.74e10}$ to $β_γ \lesssim \num{3.1e+10}$.

Finally, the software developed during the course of this thesis is
ready for data analysis for a future GridPix3 based detector.

* Version without LaTeX, using HTML 

#+begin_src html
<p>
The Standard Model of particle physics describes three out of four
known fundamental forces of nature very successfully. However, open
questions remain. One of these, the 'strong CP problem', asks why the
neutron has no electric dipole moment. This 'mathematical' problem can
be neatly solved by the introduction of a new hypothetical particle,
the <em>axion</em>. This particle can feebly interact with photons and
leptons. Axions can be produced in the core of the Sun at very high
rates. Once produced they escape the Sun. On Earth we can try to
detect them using strong magnetic fields. The latest such experiment
is the CERN Axion Solar Telescope (CAST). Axions carry the energy of
the photons which produced them, placing them in the soft X-ray energy
range.
</p>

<p>
In this thesis, a gaseous detector containing 7-GridPixes was deployed
at the CAST experiment in 2017/18 to follow up on measurements with a
single GridPix detector in 2014/15. 3150&#8201;h of background and 160&#8201;h of
solar tracking data was taken. Such data is dominated by cosmic
radiation, radioactive background and X-ray fluorescence. Methods to
suppress this background and extract the few possible axion signals
are needed. A software library 'TimepixAnalysis' was developed during
this thesis to reconstruct and analyze the CAST data.
</p>

<p>
Classification of events into background- or signal-like (X-ray) data,
uses a machine learning approach. A multilayer perceptron (type of
artificial neural network) was trained on synthetic X-rays and
background data of 6 of the 7 chips (without the axion sensitive
chip). Significant improvements to signal efficiency at comparable
background rates are achieved, compared to the method used for the old
detector.
</p>

<p>
As the solar tracking data showed no signal excess, a limit
calculation method was developed. It builds on the unbinned Bayesian
likelihood method used in the 2017 CAST Nature paper. It is extended
to allow the inclusion of systematic uncertainties as nuisance
parameters. Due to the expensive evaluation of such a likelihood
function, a Markov Chain Monte Carlo approach is used.
</p>

<p>
The limit calculation requires the 'axion image' produced by the
Lawrence Livermore National Laboratory telescope at CAST. To
characterize this, a raytracing simulation taking into account the
axion production rates in the Sun and reflection through the X-ray
optic was developed. It was verified against PANTER measurements of
the telescope.
</p>

<p>
With the software and detector advances, world best limits could be
set on the axion-electron and the chameleon coupling (another
hypothetical particle). The previous best limit on the axion-electron
coupling is improved from g<sub>ae</sub>·g<sub>a&#947;</sub> &#8818;
8.1·10<sup>-23</sup>&#8201;GeV<sup>-1</sup> to
g<sub>ae</sub>·g<sub>a&#947;</sub> &#8818;
7.35·10<sup>-23</sup>&#8201;GeV<sup>-1</sup> and the chameleon
coupling from &#946;<sub>&#947;</sub> &lt; 5.74·10<sup>10</sup> to
&#946;<sub>&#947;</sub> &#8818; 3.1·10<sup>10</sup>.
</p>

<p>
Finally, the software developed during the course of this thesis is
ready for data analysis for a future GridPix3 based detector.
</p>
#+end_src
