* PhD thesis

This repository is the git repository of my PhD thesis. It is quite
massive.

The main thesis document is a single Org file, [[file:thesis.org]]. That
might seem insane, and it is on some level, but I prefer to work on
large files relying on quick search to jump around in a file, than
having to deal with many individual files and relying on grepping
through all files to find a specific section. Personal preference and
all that. Although I have to admin that the thesis in the end did
stretch even my sanity there, at a nice ~3.1 MB in size and more than
50k lines. Well, you do what you gotta do.

The advantage of a single Org file is super convenient exporting of
the file to both LaTeX and HTML targets (although to be fair, the HTML
target needs some postprocessing, because guess what, browsers don't
like HTML pages of more than 3 MB in size 🙀). Yeah, unfortunately
that means the Org renderer of Github cannot display the Org
document. You'll have to clone the repo or look at the raw file [[https://raw.githubusercontent.com/Vindaar/phd/master/thesis.org][here]].

You can view the companion page to the thesis at:

https://phd.vindaar.de 

