
* Axions

** CAST
- A decommissioned LHC model magnet as an axion telescope
  CAST proposal
  [[file:~/org/Papers/cast_proposal_decomissioned_lhc_magnet_1999.pdf]]
  #+begin_quote
@article{ZIOUTAS1999480,
  title = {A decommissioned LHC model magnet as an axion telescope},
  journal = {Nuclear Instruments and Methods in Physics Research Section A: Accelerators, Spectrometers, Detectors and Associated Equipment},
  volume = {425},
  number = {3},
  pages = {480-487},
  year = {1999},
  issn = {0168-9002},
  doi = {https://doi.org/10.1016/S0168-9002(98)01442-9},
  url = {https://www.sciencedirect.com/science/article/pii/S0168900298014429},
  author = {K. Zioutas and C.E. Aalseth and D. Abriola and F.T.Avignone III and R.L. Brodzinski and J.I. Collar and R. Creswick and D.E.Di Gregorio and H. Farach and A.O. Gattone and C.K. Guérard and F. Hasenbalg and M. Hasinoff and H. Huck and A. Liolios and H.S. Miley and A. Morales and J. Morales and D. Nikas and S. Nussinov and A. Ortiz and E. Savvidis and S. Scopel and P. Sievers and J.A. Villar and L. Walckiers},
  keywords = {Solar axions, LHC, Superconducting magnets, Dark matter},
  abstract = {The 8.4T, 10m long transverse magnetic field of a twin aperture LHC bending magnet can be utilized as a macroscopic coherent solar axion-to-photon converter. Numerical calculations show that the integrated time of alignment with the Sun would be 33days/yr with the magnet on a tracking table capable of ±5° in the vertical direction and ±40° in the horizontal direction. The existing lower bound on the axion-to-photon coupling constant can be improved by a factor between 30 and 100 in 3yr, i.e., gaγγ≲9×10−11GeV−1 for axion masses ≲ 1eV. This value falls within the existing open axion mass window. The same set-up can simultaneously search for low- and high-energy celestial axions, or axion-like particles, scanning the sky as the Earth rotates and orbits the Sun.}
}  
  #+end_quote

- First Results from the CERN Axion Solar Telescope
  Contains, among others, an analytical expression for the solar
  axion flux:
  g₁₀ = g_aγ • 10¹⁰ GeV
  dΦ_a/dE_a = g²₁₀ 3.821•10¹⁰ cm⁻²•s⁻¹•keV⁻¹ (E_a / keV)³ / (exp(E_a / (1.103 keV)) - 1)
  results in an integrated flux:
  Φ_a = g²₁₀ 3.67•10¹¹ cm⁻²•s⁻¹
  - https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.94.121301
  - [[file:~/org/Papers/first_cast_results_physrevlett.94.121301.pdf]]
  #+begin_quote
@article{PhysRevLett.94.121301,
  title = {First Results from the CERN Axion Solar Telescope},
  author = {Zioutas, K. and Andriamonje, S. and Arsov, V. and Aune, S. and Autiero, D. and Avignone, F. T. and Barth, K. and Belov, A. and Beltr\'an, B. and Br\"auninger, H. and Carmona, J. M. and Cebri\'an, S. and Chesi, E. and Collar, J. I. and Creswick, R. and Dafni, T. and Davenport, M. and Di Lella, L. and Eleftheriadis, C. and Englhauser, J. and Fanourakis, G. and Farach, H. and Ferrer, E. and Fischer, H. and Franz, J. and Friedrich, P. and Geralis, T. and Giomataris, I. and Gninenko, S. and Goloubev, N. and Hasinoff, M. D. and Heinsius, F. H. and Hoffmann, D. H. H. and Irastorza, I. G. and Jacoby, J. and Kang, D. and K\"onigsmann, K. and Kotthaus, R. and Kr\ifmmode \check{c}\else \v{c}\fi{}mar, M. and Kousouris, K. and Kuster, M. and Laki\ifmmode \acute{c}\else \'{c}\fi{}, B. and Lasseur, C. and Liolios, A. and Ljubi\ifmmode \check{c}\else \v{c}\fi{}i\ifmmode \acute{c}\else \'{c}\fi{}, A. and Lutz, G. and Luz\'on, G. and Miller, D. W. and Morales, A. and Morales, J. and Mutterer, M. and Nikolaidis, A. and Ortiz, A. and Papaevangelou, T. and Placci, A. and Raffelt, G. and Ruz, J. and Riege, H. and Sarsa, M. L. and Savvidis, I. and Serber, W. and Serpico, P. and Semertzidis, Y. and Stewart, L. and Vieira, J. D. and Villar, J. and Walckiers, L. and Zachariadou, K.},
  collaboration = {CAST Collaboration},
  journal = {Phys. Rev. Lett.},
  volume = {94},
  issue = {12},
  pages = {121301},
  numpages = {5},
  year = {2005},
  month = {Apr},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevLett.94.121301},
  url = {https://link.aps.org/doi/10.1103/PhysRevLett.94.121301}
}
#+end_quote

- An improved limit on the axion–photon coupling from the CAST
  experiment
  Full results of phase I at CAST
  Contains a good overview on how to get from solar physics to axion
  flux!!
  Contains information about the log likelihood method that (I think)
  is mostly the same as the 2013 axion-electron paper.
  [[file:~/org/Papers/cast_phase_I_results_andriamonje2007.pdf]]
  #+begin_quote
@article{Andriamonje_2007,
	doi = {10.1088/1475-7516/2007/04/010},
	url = {https://doi.org/10.1088/1475-7516/2007/04/010},
	year = 2007,
	month = {apr},
	publisher = {{IOP} Publishing},
	volume = {2007},
	number = {04},
	pages = {010--010},
	author = {S Andriamonje and S Aune and D Autiero and K Barth and A Belov and B Beltr{\'{a}}n and H Bräuninger and J M Carmona and S Cebri{\'{a}}n and J I Collar and T Dafni and M Davenport and L Di Lella and C Eleftheriadis and J Englhauser and G Fanourakis and E Ferrer Ribas and H Fischer and J Franz and P Friedrich and T Geralis and I Giomataris and S Gninenko and H G{\'{o}}mez and M Hasinoff and F H Heinsius and D H H Hoffmann and I G Irastorza and J Jacoby and K Jakov{\v{c}}i{\'{c}} and D Kang and K Königsmann and R Kotthaus and M Kr{\v{c}}mar and K Kousouris and M Kuster and B Laki{\'{c}} and C Lasseur and A Liolios and A Ljubi{\v{c}}i{\'{c}} and G Lutz and G Luz{\'{o}}n and D Miller and A Morales and J Morales and A Ortiz and T Papaevangelou and A Placci and G Raffelt and H Riege and A Rodr{\'{\i}}guez and J Ruz and I Savvidis and Y Semertzidis and P Serpico and L Stewart and J Vieira and J Villar and J Vogel and L Walckiers and K Zioutas and CAST Collaboration},
	title = {An improved limit on the axion{\textendash}photon coupling from the {CAST} experiment},
	journal = {Journal of Cosmology and Astroparticle Physics},
	abstract = {We have searched for solar axions or similar particles that couple to two photons by using the CERN Axion Solar Telescope (CAST) set-up with improved conditions in all detectors. From the absence of excess x-rays when the magnet was pointing to the Sun, we set an upper limit on the axion–photon coupling of gaγ<8.8 × 10−11 GeV−1 at 95% CL for . This result is the best experimental limit over a broad range of axion masses and for also supersedes the previous limit derived from energy-loss arguments on globular cluster stars.}
}  
  #+end_quote

- Probing the eV-scale axions with CAST
  Contains first results of CAST phase II. 4He 2005 to 2007, then 3He
  results in 2008 (continued on until 2011, other paper below).
  [[file:~/org/Papers/probing_ev_scale_axions_cast_E._Arik_2009_J._Cosmol._Astropart._Phys._2009_008.pdf]]
  #+begin_quote
@article{Arik_2009,
	doi = {10.1088/1475-7516/2009/02/008},
	url = {https://doi.org/10.1088/1475-7516/2009/02/008},
	year = 2009,
	month = {feb},
	publisher = {{IOP} Publishing},
	volume = {2009},
	number = {02},
	pages = {008--008},
	author = {E Arik and S Aune and D Autiero and K Barth and A Belov and B Beltr{\'{a}}n and S Borghi and G Bourlis and F.S Boydag and H Bräuninger and J.M Carmona and S Cebri{\'{a}}n and S.A Cetin and J.I Collar and T Dafni and M Davenport and L. Di Lella and O.B Dogan and C Eleftheriadis and N Elias and G Fanourakis and E Ferrer-Ribas and H Fischer and P Friedrich and J Franz and J Gal{\'{a}}n and T Geralis and I Giomataris and S Gninenko and H G{\'{o}}mez and R Hartmann and M Hasinoff and F.H Heinsius and I Hikmet and D.H.H Hoffmann and I.G Irastorza and J Jacoby and K Jakov{\v{c}}i{\'{c}} and D Kang and K Königsmann and R Kotthaus and M Kr{\v{c}}mar and K Kousouris and M Kuster and B Laki{\'{c}} and C Lasseur and A Liolios and A Ljubi{\v{c}}i{\'{c}} and G Lutz and G Luz{\'{o}}n and D Miller and J Morales and T Niinikoski and A Nordt and A Ortiz and T Papaevangelou and M.J Pivovaroff and A Placci and G Raffelt and H Riege and A Rodr{\'{\i}}guez and J Ruz and I Savvidis and Y Semertzidis and P Serpico and R Soufli and L Stewart and K. van Bibber and J Villar and J Vogel and L Walckiers and K Zioutas},
	title = {Probing {eV}-scale axions with {CAST}},
	journal = {Journal of Cosmology and Astroparticle Physics},
	abstract = {We have searched for solar axions or other pseudoscalar particles that couple to two photons by using the CERN Axion Solar Telescope (CAST) setup. Whereas we previously have reported results from CAST with evacuated magnet bores (Phase I), setting limits on lower mass axions, here we report results from CAST where the magnet bores were filled with 4He gas (Phase II) of variable pressure. The introduction of gas generates a refractive photon mass mγ, thereby achieving the maximum possible conversion rate for those axion masses ma that match mγ. With 160 different pressure settings we have scanned ma up to about 0.4 eV, taking approximately 2 h of data for each setting. From the absence of excess x-rays when the magnet was pointing to the Sun, we set a typical upper limit on the axion-photon coupling of gaγ≲2.2 × 10−10 GeV−1 at 95% CL for ma≲0.4 eV, the exact result depending on the pressure setting. The excluded parameter range covers realistic axion models with a Peccei-Quinn scale in the neighborhood of fa ∼ 107 GeV. Currently in the second part of CAST Phase II, we are searching for axions with masses up to about 1.2 eV using 3He as a buffer gas.}
}  
  #+end_quote

- New solar axion search using the CERN Axion Solar Telescope with $^{4}\mathrm{He}$ filling
  Contains overview of 4He (the first) and 3He buffer gas data
  takings.
  Contains information about unbinned log likelihood method also used
  in nature paper!
  [[file:~/org/Papers/new_solar_axion_search_cast_4he_2015_PhysRevD.92.021101.pdf]]
  #+begin_quote
@article{PhysRevD.92.021101,
  title = {New solar axion search using the CERN Axion Solar Telescope with $^{4}\mathrm{He}$ filling},
  author = {Arik, M. and Aune, S. and Barth, K. and Belov, A. and Br\"auninger, H. and Bremer, J. and Burwitz, V. and Cantatore, G. and Carmona, J. M. and Cetin, S. A. and Collar, J. I. and Da Riva, E. and Dafni, T. and Davenport, M. and Dermenev, A. and Eleftheriadis, C. and Elias, N. and Fanourakis, G. and Ferrer-Ribas, E. and Gal\'an, J. and Garc\'{\i}a, J. A. and Gardikiotis, A. and Garza, J. G. and Gazis, E. N. and Geralis, T. and Georgiopoulou, E. and Giomataris, I. and Gninenko, S. and G\'omez Marzoa, M. and Hasinoff, M. D. and Hoffmann, D. H. H. and Iguaz, F. J. and Irastorza, I. G. and Jacoby, J. and Jakov\ifmmode \check{c}\else \v{c}\fi{}i\ifmmode \acute{c}\else \'{c}\fi{}, K. and Karuza, M. and Kavuk, M. and Kr\ifmmode \check{c}\else \v{c}\fi{}mar, M. and Kuster, M. and Laki\ifmmode \acute{c}\else \'{c}\fi{}, B. and Laurent, J. M. and Liolios, A. and Ljubi\ifmmode \check{c}\else \v{c}\fi{}i\ifmmode \acute{c}\else \'{c}\fi{}, A. and Luz\'on, G. and Neff, S. and Niinikoski, T. and Nordt, A. and Ortega, I. and Papaevangelou, T. and Pivovaroff, M. J. and Raffelt, G. and Rodr\'{\i}guez, A. and Rosu, M. and Ruz, J. and Savvidis, I. and Shilon, I. and Solanki, S. K. and Stewart, L. and Tom\'as, A. and Vafeiadis, T. and Villar, J. and Vogel, J. K. and Yildiz, S. C. and Zioutas, K.},
  collaboration = {CAST Collaboration},
  journal = {Phys. Rev. D},
  volume = {92},
  issue = {2},
  pages = {021101},
  numpages = {6},
  year = {2015},
  month = {Jul},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevD.92.021101},
  url = {https://link.aps.org/doi/10.1103/PhysRevD.92.021101}
}
  #+end_quote

** g_ae - Axion electron limits

- CAST constraints on the axion-electron coupling
  The paper from 2013 about the axion electron coupling.
  [[file:~/org/Papers/cast_axion_electron_jcap_2013_pnCCD.pdf]]
  #+begin_quote
@article{Barth_2013,
	doi = {10.1088/1475-7516/2013/05/010},
	url = {https://doi.org/10.1088/1475-7516/2013/05/010},
	year = 2013,
	month = {may},
	publisher = {{IOP} Publishing},
	volume = {2013},
	number = {05},
	pages = {010--010},
	author = {K Barth and A Belov and B Beltran and H Bräuninger and J.M Carmona and J.I Collar and T Dafni and M Davenport and L. Di Lella and C Eleftheriadis and J Englhauser and G Fanourakis and E Ferrer-Ribas and H Fischer and J Franz and P Friedrich and J Gal{\'{a}}n and J.A Garc{\'{\i}}a and T Geralis and I Giomataris and S Gninenko and H G{\'{o}}mez and M.D Hasinoff and F.H Heinsius and D.H.H Hoffmann and I.G Irastorza and J Jacoby and K Jakov{\v{c}}i{\'{c}} and D Kang and K Königsmann and R Kotthaus and K Kousouris and M Kr{\v{c}}mar and M Kuster and B Laki{\'{c}} and A Liolios and A Ljubi{\v{c}}i{\'{c}} and G Lutz and G Luz{\'{o}}n and D.W Miller and T Papaevangelou and M.J Pivovaroff and G Raffelt and J Redondo and H Riege and A Rodr{\'{\i}}guez and J Ruz and I Savvidis and Y Semertzidis and L Stewart and K. Van Bibber and J.D Vieira and J.A Villar and J.K Vogel and L Walckiers and K Zioutas},
	title = {{CAST} constraints on the axion-electron coupling},
	journal = {Journal of Cosmology and Astroparticle Physics},
	abstract = {In non-hadronic axion models, which have a tree-level axion-electron interaction, the Sun produces a strong axion flux by bremsstrahlung, Compton scattering, and axio-recombination, the ``BCA processes.'' Based on a new calculation of this flux, including for the first time axio-recombination, we derive limits on the axion-electron Yukawa coupling gae and axion-photon interaction strength gaγ using the CAST phase-I data (vacuum phase). For ma≲10 meV/c2 we find gaγ gae < 8.1 × 10−23 GeV−1 at 95% CL. We stress that a next-generation axion helioscope such as the proposed IAXO could push this sensitivity into a range beyond stellar energy-loss limits and test the hypothesis that white-dwarf cooling is dominated by axion emission.}
}
  #+end_quote

- Solar axion flux from the axion-electron coupling
  The accompanying theory paper about the solar axion-electron flux
  [[file:~/org/Papers/solar_axion_electron_flux_redondo2013.pdf]]
  #+begin_quote
@article{Redondo_2013,
	doi = {10.1088/1475-7516/2013/12/008},
	url = {https://doi.org/10.1088/1475-7516/2013/12/008},
	year = 2013,
	month = {dec},
	publisher = {{IOP} Publishing},
	volume = {2013},
	number = {12},
	pages = {008--008},
	author = {Javier Redondo},
	title = {Solar axion flux from the axion-electron coupling},
	journal = {Journal of Cosmology and Astroparticle Physics},
	abstract = {In non-hadronic axion models, where axions couple to electrons at tree level, the solar axion flux is completely dominated by the ABC reactions (Atomic recombination and deexcitation, Bremsstrahlung and Compton). In this paper the ABC flux is computed from available libraries of monochromatic photon radiative opacities (OP, LEDCOP and OPAS) by exploiting the relations between axion and photon emission cross sections. These results turn to be ∼ 30% larger than previous estimates due to atomic recombination (free-bound electron transitions) and deexcitation (bound-bound), which where not previously taken into account.}
}
  #+end_quote

** g_aγ - Axion photon limits

- New CAST limit on the axion--photon interaction
  CAST nature paper.
  [[file:~/org/Papers/nature_cast_limit_axion_photon_nphys4109.pdf]]
  #+begin_quote
@article{cast_nature,
  title={New CAST limit on the axion--photon interaction},
  author={Collaboration, CAST and others},
  journal={Nature Physics},
  volume={13},
  pages={584--590},
  url={https://www.nature.com/articles/nphys4109},
  year={2017}
}
  #+end_quote


** β_γ - Chameleon limits

- Search for solar chameleons with an InGrid based X-ray detector at the CAST experiment
  #+begin_quote
@article{krieger2018search,
  title={Search for solar chameleons with an InGrid based X-ray detector at the CAST experiment},
  author={Krieger, Christoph},
  year={2018},
  publisher={Universit{\"a}ts-und Landesbibliothek Bonn}
}
  #+end_quote

  
  
*** Telescopes

- Spiegelsysteme streifenden Einfalls als abbildende Optiken für
  Röntgenstrahlen
  The paper by Hans Wolter introducing the I type X-ray optics
  [[file:~/org/Papers/wolter_type_1_1952_andp.19524450108.pdf]]
  #+begin_quote
@article{wolter_1_type,
  author = {Wolter, Hans},
  title = {Spiegelsysteme streifenden Einfalls als abbildende Optiken für Röntgenstrahlen},
  journal = {Annalen der Physik},
  volume = {445},
  number = {1-2},
  pages = {94-114},
  doi = {https://doi.org/10.1002/andp.19524450108},
  url = {https://onlinelibrary.wiley.com/doi/abs/10.1002/andp.19524450108},
  eprint = {https://onlinelibrary.wiley.com/doi/pdf/10.1002/andp.19524450108},
  abstract = {Als Optiken zur Röntgenstrahlmikroskopie eignen sich Systeme von total-reflektierenden Spiegeln, die bei Hebung der sphärischen Aberration für einen Achsenpunkt zugleich die Abbesche Sinusbedingung bis zu Aperturen 0,05 befriedigend erfüllen. Für die Lebenduntersuchung biologischer Objekte empfehlen sich Wellenlängen um 24 Å, die im Wasser wenig, aber in kohlenstoffhaltigen oder stickstoffhaltigen Stoffen stark absorbiert werden. Mit diesen weichen Strahlen ist eine Steigerung des Auflösungsvermögens gegenüber dem Lichtmikroskop um mindestens eine Größenordnung unter Verwendung der hier beschriebenen Optiken zu erwarten.},
  year = {1952}
}
  #+end_quote

- Conical imaging mirrors for high-speed x-ray telescopes
  Apparently a paper that expands on the Wolter paper for actual
  applications by using a conical design?
  [[file:~/org/Papers/conical_xray_telescopes_petre1985.pdf]]
  #+begin_quote
@article{Petre:85,
  oauthor = {Robert Petre and Peter J. Serlemitsos},
  journal = {Appl. Opt.},
  keywords = {Optical systems; Radiation detectors; Spatial resolution; X ray imaging; X ray mirrors; X ray telescopes},
  number = {12},
  pages = {1833--1837},
  publisher = {OSA},
  title = {Conical imaging mirrors for high-speed x-ray telescopes},
  volume = {24},
  month = {Jun},
  year = {1985},
  url = {http://ao.osa.org/abstract.cfm?URI=ao-24-12-1833},
  doi = {10.1364/AO.24.001833},
  abstract = {The conical x-ray imaging mirror represents the long focal length limit of a Wolter type I grazing incidence mirror, in which the curved surfaces have been replaced by simple cones. When many thin-walled cones are nested, such a mirror affords the relatively high aperture filling factor needed for telescopes well suited to broadband x-ray astonomy. A conical mirror also features a constant spatial resolution across the field of view and can be designed to have an arbitrarily high intrinsic spatial resolution. We describe the spatial resolution and filling factor of conical optics as a function of various design parameters as characterized using a Monte Carlo ray tracing procedure.},
}
  #+end_quote
  

**** ABRIXAS

- The x-ray telescope of CAST
  [[~/org/Papers/cast_xray_telescope_abrixas_Kuster_2007_New_J._Phys._9_169.pdf]]
  #+begin_quote
@article{CAST_telescope_ccd,
  author={M Kuster and H Bräuninger and S Cebrián and M Davenport and C Eleftheriadis and J Englhauser and H Fischer and J Franz and P
Friedrich and R Hartmann and F H Heinsius and D H H Hoffmann and G Hoffmeister and J N Joux and D Kang and K Königsmann and R
Kotthaus and T Papaevangelou and C Lasseur and A Lippitsch and G Lutz and J Morales and A Rodríguez and L Strüder and J Vogel and 
Zioutas},
  title={The x-ray telescope of CAST},
  journal={New Journal of Physics},
  volume={9},
  number={6},
  pages={169},
  url={http://stacks.iop.org/1367-2630/9/i=6/a=169},
  year={2007},
}
  #+end_quote

- ABRIXAS: an imaging x-ray survey in the 0.5- to 10-keV range
  Details about the ABRIXAS X-ray telescope
  [[file:~/org/Papers/abrixas_telescope_mpe_cast_12.331248.pdf]]  
  #+begin_quote
@inproceedings{ABRIXAS_0,
  author = {Peter Friedrich},
  title = {{ABRIXAS: an imaging x-ray survey in the 0.5- to 10-keV range}},
  volume = {3444},
  booktitle = {X-Ray Optics, Instruments, and Missions},
  editor = {Richard B. Hoover and Arthur B. C. Walker II},
  organization = {International Society for Optics and Photonics},
  publisher = {SPIE},
  pages = {342 -- 349},
  year = {1998},
  doi = {},
  URL = {https://doi.org/10.1117/12.331248}
}

@article{article,
  author = {Friedrich, P. and Hasinger, Gunther and Richter, G. and Fritze, K. and Trümper, J. and Bräuninger, H. and Predehl, P. and Staubert, Ruediger and Kendziorra, E.},
  year = {1996},
  month = {01},
  pages = {681-682},
  title = {ABRIXAS, an imaging telescope for a 0.5-10 keV survey.},
  volume = {-1}
}
  #+end_quote

- Mirror system for the German x-ray satellite ABRIXAS: I. Flight
  mirror fabrication, integration, and testing
  [[file:~/org/Papers/abrixas_mirror_system_integration_testing_1998_12.331249.pdf]]
  #+begin_quote
@inproceedings{ABRIXAS_1,
  author = {Juergen Altmann and Wilhelm J. Egle and Ulrich Bingel and Wolfgang Hafner and Bernhard Gaenswein and Herbert Schwarz and Anton Neugschwender},
  title = {{Mirror system for the German x-ray satellite ABRIXAS: I. Flight mirror fabrication, integration, and testing}},
  volume = {3444},
  booktitle = {X-Ray Optics, Instruments, and Missions},
  editor = {Richard B. Hoover and Arthur B. C. Walker II},
  organization = {International Society for Optics and Photonics},
  publisher = {SPIE},
  pages = {350 -- 358},
  year = {1998},
  doi = {},
  URL = {https://doi.org/10.1117/12.331249}
}
  #+end_quote

- Mirror system for the German x-ray satellite ABRIXAS: II. Design and
  mirror development
  [[file:~/org/Papers/abrixas_mirror_system_design_development_12.331250.pdf]]
  #+begin_quote
@inproceedings{ABRIXAS_2,
  author = {Wilhelm J. Egle and Juergen Altmann and Paul Kaufmann and Hartmut Muenker and Gerhard Derst and Herbert Schwarz and Anton Neugschwender},
  title = {{Mirror system for the German x-ray satellite ABRIXAS: II. Design and mirror development}},
  volume = {3444},
  booktitle = {X-Ray Optics, Instruments, and Missions},
  editor = {Richard B. Hoover and Arthur B. C. Walker II},
  organization = {International Society for Optics and Photonics},
  publisher = {SPIE},
  pages = {359 -- 368},
  year = {1998},
  doi = {},
  URL = {https://doi.org/10.1117/12.331250}
}
  #+end_quote

**** LLNL telescope

- X-ray optics in new instruments for astro- and astroparticle physics
  The PhD thesis that studied the optimizations for the LLNL telescope
  [[file:~/org/Papers/llnl_telescope_optimizations_phdthesis_for_DTU_orbit.pdf]]
  #+begin_quote
@phdthesis{9d8b4de98f0542e9bbe71fe572f3d3f5,
  title = "X-ray optics in new instruments for astro- and astroparticle physics",
  abstract = "Discovering new phenomena in physics require ever larger and more advanced instruments in order to detect either fundamental particles or energetic events in the universe. This thesis describes the work done on three separate X-ray telescopes, one for astrophysics and two for astroparticle physics; all of which makes use of grazing incidence reflecting X-ray optics.Reflective coatings using various materials on Silicon Pore Optic (SPO) substrates were investigated for the European Athena large X-ray telescope mission. Ir/B4C single bilayer and multilayer coatings were characterised and qualified for long term stability and reflectivity performance. A Cr sublayer under an Ir/B4C coating was seen to mitigate the film stress; additionally, Ir coatings were found to show a smoothening effect when deposited onto a rough Cr surface. The coating production upscaling to 210,000 SPO substrates coated over a two year period is discussed and a multi chamber solution is described.An X-ray telescope for the CAST helioscope at CERN was designed, optimised, produced and installed in order to improve the sensitivity of the helioscope. The installed telescope focuses X-rays, converted from axions through the Primakoff effect, into a detector area 400 times smaller than before. Measurements using an X-ray source shows the telescope behaving as calculated through ray tracing.A successor to the CAST helioscope named the International AXion Observatory (IAXO) is in the definition phase and X-ray telescopes to the much larger instrument was designed. Software was developed to calculate the optimal focal length based on estimated telescope figure error and angular size of the sun.A new software solution for the coating facility at DTU Space was developed using the SPEC software package, improving the flexibility and capability of the setup. The instruments connected to the coating chamber were all implemented. Coatings for the CAST X-ray telescope and Athena coating qualifications were done using the new software.",
  author = "Jakobsen, {Anders Clemen}",
  year = "2015",
  language = "English",
  isbn = "978-87-91694-28-8",
  publisher = "DTU Space",
}
  #+end_quote

- A Micromegas-based low-background x-ray detector coupled to a slumped-glass telescope for axion research
  First paper publishing results using the LLNL telesope at CAST
  [[file:~/org/Papers/llnl_telescope_cast_mm_1509_06190.pdf]]
  #+begin_quote
@article{llnl_telescope_first_cast_results,
  author = {Aznar, Francisco and Castel, Juan Francisco and Christensen, FE and Dafni, Theopisti and Decker, Todd and Ferrer Ribas, Esther and Garcia, J. and Giomataris, Ioannis and Garza, J. and Hailey, CJ},
  year = {2015},
  month = {01},
  pages = {008},
  title = {A Micromegas-based low-background x-ray detector coupled to a slumped-glass telescope for axion research},
  volume = {2015},
  journal = {Journal of Cosmology and Astroparticle Physics}
} 
  #+end_quote

***** Nustar

- THE NUCLEAR SPECTROSCOPIC TELESCOPE ARRAY (NuSTAR) HIGH-ENERGY X-RAY
  MISSION
  Paper introducing the NuStar mission
  [[file:~/org/Papers/nustar_introduction_Harrison_2013_ApJ_770_103.pdf]]
  #+begin_quote
@article{Harrison_2013,
	doi = {10.1088/0004-637x/770/2/103},
	url = {https://doi.org/10.1088/0004-637x/770/2/103},
	year = 2013,
	month = {may},
	publisher = {American Astronomical Society},
	volume = {770},
	number = {2},
	pages = {103},
	author = {Fiona A. Harrison and William W. Craig and Finn E. Christensen and Charles J. Hailey and William W. Zhang and Steven E. Boggs and Daniel Stern and W. Rick Cook and Karl Forster and Paolo Giommi and Brian W. Grefenstette and Yunjin Kim and Takao Kitaguchi and Jason E. Koglin and Kristin K. Madsen and Peter H. Mao and Hiromasa Miyasaka and Kaya Mori and Matteo Perri and Michael J. Pivovaroff and Simonetta Puccetti and Vikram R. Rana and Niels J. Westergaard and Jason Willis and Andreas Zoglauer and Hongjun An and Matteo Bachetti and Nicolas M. Barri{\`{e}}re and Eric C. Bellm and Varun Bhalerao and Nicolai F. Brejnholt and Felix Fuerst and Carl C. Liebe and Craig B. Markwardt and Melania Nynka and Julia K. Vogel and Dominic J. Walton and Daniel R. Wik and David M. Alexander and Lynn R. Cominsky and Ann E. Hornschemeier and Allan Hornstrup and Victoria M. Kaspi and Greg M. Madejski and Giorgio Matt and Silvano Molendi and David M. Smith and John A. Tomsick and Marco Ajello and David R. Ballantyne and Mislav Balokovi{\'{c}} and Didier Barret and Franz E. Bauer and Roger D. Blandford and W. Niel Brandt and Laura W. Brenneman and James Chiang and Deepto Chakrabarty and Jerome Chenevez and Andrea Comastri and Francois Dufour and Martin Elvis and Andrew C. Fabian and Duncan Farrah and Chris L. Fryer and Eric V. Gotthelf and Jonathan E. Grindlay and David J. Helfand and Roman Krivonos and David L. Meier and Jon M. Miller and Lorenzo Natalucci and Patrick Ogle and Eran O. Ofek and Andrew Ptak and Stephen P. Reynolds and Jane R. Rigby and Gianpiero Tagliaferri and Stephen E. Thorsett and Ezequiel Treister and C. Megan Urry},
	title = {{THENUCLEAR} {SPECTROSCOPIC} {TELESCOPE} {ARRAY}({NuSTAR}) {HIGH}-{ENERGY} X-{RAY} {MISSION}},
	journal = {The Astrophysical Journal},
	abstract = {The Nuclear Spectroscopic Telescope Array (NuSTAR) mission, launched on 2012 June 13, is the first focusing high-energy X-ray telescope in orbit. NuSTAR operates in the band from 3 to 79 keV, extending the sensitivity of focusing far beyond the ∼10 keV high-energy cutoff achieved by all previous X-ray satellites. The inherently low background associated with concentrating the X-ray light enables NuSTAR to probe the hard X-ray sky with a more than 100-fold improvement in sensitivity over the collimated or coded mask instruments that have operated in this bandpass. Using its unprecedented combination of sensitivity and spatial and spectral resolution, NuSTAR will pursue five primary scientific objectives: (1) probe obscured active galactic nucleus (AGN) activity out to the peak epoch of galaxy assembly in the universe (at z ≲ 2) by surveying selected regions of the sky; (2) study the population of hard X-ray-emitting compact objects in the Galaxy by mapping the central regions of the Milky Way; (3) study the non-thermal radiation in young supernova remnants, both the hard X-ray continuum and the emission from the radioactive element 44Ti; (4) observe blazars contemporaneously with ground-based radio, optical, and TeV telescopes, as well as with Fermi and Swift, to constrain the structure of AGN jets; and (5) observe line and continuum emission from core-collapse supernovae in the Local Group, and from nearby Type Ia events, to constrain explosion models. During its baseline two-year mission, NuSTAR will also undertake a broad program of targeted observations. The observatory consists of two co-aligned grazing-incidence X-ray telescopes pointed at celestial targets by a three-axis stabilized spacecraft. Deployed into a 600 km, near-circular, 6° inclination orbit, the observatory has now completed commissioning, and is performing consistent with pre-launch expectations. NuSTAR is now executing its primary science mission, and with an expected orbit lifetime of 10 yr, we anticipate proposing a guest investigator program, to begin in late 2014.}
}  
  #+end_quote

- Development of the HEFT and NuSTAR focusing telescopes
  1st paper introducing techniques used for nustar
  [[file:~/org/Papers/development_nustar_focusing_telescope_harrison2006.pdf]]
  #+begin_quote
@Inbook{Harrison2006,
  author="Harrison, Fiona A.
  and Christensen, Finn E.
  and Craig, William
  and Hailey, Charles
  and Baumgartner, Wayne
  and Chen, C. M. H.
  and Chonko, James
  and Cook, W. Rick
  and Koglin, Jason
  and Madsen, Kristin-Kruse
  and Pivavoroff, Michael
  and Boggs, Steven
  and Smith, David",
  editor="von Ballmoos, Peter",
  title="Development of the HEFT and NuSTAR focusing telescopes",
  bookTitle="Focusing Telescopes in Nuclear Astrophysics",
  year="2006",
  publisher="Springer Netherlands",
  address="Dordrecht",
  pages="131--137",
  abstract="Hard X-ray/soft gamma-ray astrophysics is on the verge of a major advance with the practical realization of technologies capable of efficiently focusing X-rays above 10 keV. Hard X-ray focusing telescopes can achieve orders of magnitude improvements in sensitivity compared to the instruments based on coded apertures and collimated detectors that have traditionally been employed in this energy band. Compact focal planes enable high-performance detectors with good spectral resolution to be employed in efficient, low-background configurations. We have developed multilayer coated grazing incidence optics and solid state Cadmium Zinc Telluride focal plane systems for the High Energy Focusing Telescope (HEFT) balloon-borne experiment, and for the Nuclear Spectroscopic Telescope Array (NuSTAR) Small Explorer satellite. In this paper we describe the technologies, telescope designs, and performance of both experiments.",
  isbn="978-1-4020-5304-7",
  doi="10.1007/978-1-4020-5304-7_15",
  url="https://doi.org/10.1007/978-1-4020-5304-7_15"
}
  #+end_quote

- NuSTAR hard x-ray optics design and performance
  2nd paper introducing techniques used in Nustar telescope
  [[file:~/org/Papers/nustar_optics_design_performance_koglin2009.pdf]]
  #+begin_quote
@inproceedings{nustar_design_performance,
  author = {Jason E. Koglin and HongJun An and Kenneth L. Blaedel and Nicolai F. Brejnholt and Finn E. Christensen and William W. Craig and Todd A. Decker and Charles J. Hailey and Layton C. Hale and Fiona A. Harrison and Carsten P. Jensen and Kristin K. Madsen and Kaya Mori and Michael J. Pivovaroff and Gordon Tajiri and William W. Zhang},
  title = {{NuSTAR hard x-ray optics design and performance}},
  volume = {7437},
  booktitle = {Optics for EUV, X-Ray, and Gamma-Ray Astronomy IV},
  editor = {Stephen L. O'Dell and Giovanni Pareschi},
  organization = {International Society for Optics and Photonics},
  publisher = {SPIE},
  pages = {107 -- 114},
  keywords = {Hard X-ray telescope, X-ray optics, segmented glass, NuSTAR},
  year = {2009},
  doi = {},
  URL = {https://doi.org/10.1117/12.826724}
}
  #+end_quote

- Fabrication of the NuSTAR flight optics
  3rd paper introducing techniques used for nustar telescope
  [[file:~/org/Papers/nustar_fabrication_craig2011.pdf]]
  #+begin_quote
@inproceedings{nustar_fabrication,
  author = {William W. Craig and HongJun An and Kenneth L. Blaedel and Finn E. Christensen and Todd A. Decker and Anne Fabricant and Jeff Gum and Charles J. Hailey and Layton Hale and Carsten B. Jensen and Jason E. Koglin and Kaya Mori and Melanie Nynka and Michael J. Pivovaroff and Marton V. Sharpe and Marcela Stern and Gordon Tajiri and William W. Zhang},
  title = {{Fabrication of the NuSTAR flight optics}},
  volume = {8147},
  booktitle = {Optics for EUV, X-Ray, and Gamma-Ray Astronomy V},
  editor = {Stephen L. O'Dell and Giovanni Pareschi},
  organization = {International Society for Optics and Photonics},
  publisher = {SPIE},
  pages = {151 -- 164},
  keywords = {Hard X-ray telescope, X-ray optics, NuSTAR, thermally-slumped glass},
  year = {2011},
  doi = {},
  URL = {https://doi.org/10.1117/12.895278}
}
  #+end_quote

- The Nuclear Spectroscopic Telescope Array (NuSTAR): optics overview
  and current status
  4th paper introducing nustar telescope
  [[file:~/org/Papers/nustar_overview_status_hailey2010.pdf]]
  #+begin_quote
@inproceedings{nustar_overview_status,
  author = {Charles J. Hailey and HongJun An and Kenneth L. Blaedel and Nicolai F. Brejnholt and Finn E. Christensen and William W. Craig and Todd A. Decker and Melanie Doll and Jeff Gum and Jason E. Koglin and Carsten P. Jensen and Layton Hale and Kaya Mori and Michael J. Pivovaroff and Marton Sharpe and Marcela Stern and Gordon Tajiri and William W. Zhang},
  title = {{The Nuclear Spectroscopic Telescope Array (NuSTAR): optics overview and current status}},
  volume = {7732},
  booktitle = {Space Telescopes and Instrumentation 2010: Ultraviolet to Gamma Ray},
  editor = {Monique Arnaud and Stephen S. Murray and Tadayuki Takahashi},
  organization = {International Society for Optics and Photonics},
  publisher = {SPIE},
  pages = {197 -- 209},
  keywords = {Hard X-ray telescope, X-ray optics, thermally-slumped glass, NuSTAR},
  year = {2010},
  doi = {},
  URL = {https://doi.org/10.1117/12.857654}
}
  #+end_quote

** IAXO

- Towards a new generation axion helioscope
  First paper about IAXO?
  [[file:~/org/Papers/towards_a_new_generation_axion_helioscope_2011_I.G._Irastorza_2011_J._Cosmol._Astropart._Phys._2011_013.pdf]]
  #+begin_quote
@article{Irastorza_2011,
	doi = {10.1088/1475-7516/2011/06/013},
	url = {https://doi.org/10.1088/1475-7516/2011/06/013},
	year = 2011,
	month = {jun},
	publisher = {{IOP} Publishing},
	volume = {2011},
	number = {06},
	pages = {013--013},
	author = {I.G Irastorza and F.T Avignone and S Caspi and J.M Carmona and T Dafni and M Davenport and A Dudarev and G Fanourakis and E Ferrer-Ribas and J Gal{\'{a}}n and J.A Garc{\'{\i}}a and T Geralis and I Giomataris and H G{\'{o}}mez and D.H.H Hoffmann and F.J Iguaz and K Jakov{\v{c}}i{\'{c}} and M Kr{\v{c}}mar and B Laki{\'{c}} and G Luz{\'{o}}n and M Pivovaroff and T Papaevangelou and G Raffelt and J Redondo and A Rodr{\'{\i}}guez and S Russenschuck and J Ruz and I Shilon and H. Ten Kate and A Tom{\'{a}}s and S Troitsky and K. van Bibber and J.A Villar and J Vogel and L Walckiers and K Zioutas},
	title = {Towards a new generation axion helioscope},
	journal = {Journal of Cosmology and Astroparticle Physics},
	abstract = {We study the feasibility of a new generation axion helioscope, the most ambitious and promising detector of solar axions to date. We show that large improvements in magnetic field volume, x-ray focusing optics and detector backgrounds are possible beyond those achieved in the CERN Axion Solar Telescope (CAST). For hadronic models, a sensitivity to the axion-photon coupling of gaγ ≳ few × 10−12 GeV−1 is conceivable, 1–1.5 orders of magnitude beyond the CAST sensitivity. If axions also couple to electrons, the Sun produces a larger flux for the same value of the Peccei-Quinn scale, allowing one to probe a broader class of models. Except for the axion dark matter searches, this experiment will be the most sensitive axion search ever, reaching or surpassing the stringent bounds from SN1987A and possibly testing the axion interpretation of anomalous white-dwarf cooling that predicts ma of a few meV. Beyond axions, this new instrument will probe entirely unexplored ranges of parameters for a large variety of axion-like particles (ALPs) and other novel excitations at the low-energy frontier of elementary particle physics.}
}  
  #+end_quote

- IAXO-the international axion observatory
  First "named" paper about IAXO  
  [[file:~/org/Papers/the_international_axion_observatory_2013_1302.3273.pdf]]
  #+begin_quote
@article{vogel2013iaxo,
  title={IAXO-the international axion observatory},
  author={Vogel, JK and Avignone, FT and Cantatore, G and Carmona, JM and Caspi, S and Cetin, SA and Christensen, FE and Dael, A and Dafni, T and Davenport, M and others},
  journal={arXiv preprint arXiv:1302.3273},
  year={2013}
}  
  #+end_quote

- Conceptual design of the International Axion Observatory (IAXO)
  [[file:~/org/Papers/conceptual_design_iaxo_2014_Armengaud_2014_J._Inst._9_T05002.pdf]]
  #+begin_quote
@article{Armengaud_2014,
	doi = {10.1088/1748-0221/9/05/t05002},
	url = {https://doi.org/10.1088/1748-0221/9/05/t05002},
	year = 2014,
	month = {may},
	publisher = {{IOP} Publishing},
	volume = {9},
	number = {05},
	pages = {T05002--T05002},
	author = {E Armengaud and F T Avignone and M Betz and P Brax and P Brun and G Cantatore and J M Carmona and G P Carosi and F Caspers and S Caspi and S A Cetin and D Chelouche and F E Christensen and A Dael and T Dafni and M Davenport and A V Derbin and K Desch and A Diago and B Döbrich and I Dratchnev and A Dudarev and C Eleftheriadis and G Fanourakis and E Ferrer-Ribas and J Gal{\'{a}}n and J A Garc{\'{\i}}a and J G Garza and T Geralis and B Gimeno and I Giomataris and S Gninenko and H G{\'{o}}mez and D Gonz{\'{a}}lez-D{\'{\i}}az and E Guendelman and C J Hailey and T Hiramatsu and D H H Hoffmann and D Horns and F J Iguaz and I G Irastorza and J Isern and K Imai and A C Jakobsen and J Jaeckel and K Jakov{\v{c}}i{\'{c}} and J Kaminski and M Kawasaki and M Karuza and M Kr{\v{c}}mar and K Kousouris and C Krieger and B Laki{\'{c}} and O Limousin and A Lindner and A Liolios and G Luz{\'{o}}n and S Matsuki and V N Muratova and C Nones and I Ortega and T Papaevangelou and M J Pivovaroff and G Raffelt and J Redondo and A Ringwald and S Russenschuck and J Ruz and K Saikawa and I Savvidis and T Sekiguchi and Y K Semertzidis and I Shilon and P Sikivie and H Silva and H ten Kate and A Tomas and S Troitsky and T Vafeiadis and K van Bibber and P Vedrine and J A Villar and J K Vogel and L Walckiers and A Weltman and W Wester and S C Yildiz and K Zioutas},
	title = {Conceptual design of the International Axion Observatory ({IAXO})},
	journal = {Journal of Instrumentation},
	abstract = {The International Axion Observatory (IAXO) will be a forth generation axion helioscope. As its primary physics goal, IAXO will look for axions or axion-like particles (ALPs) originating in the Sun via the Primakoff conversion of the solar plasma photons. In terms of signal-to-noise ratio, IAXO will be about 4–5 orders of magnitude more sensitive than CAST, currently the most powerful axion helioscope, reaching sensitivity to axion-photon couplings down to a few × 10−12 GeV−1 and thus probing a large fraction of the currently unexplored axion and ALP parameter space. IAXO will also be sensitive to solar axions produced by mechanisms mediated by the axion-electron coupling gae with sensitivity — for the first time — to values of gae not previously excluded by astrophysics. With several other possible physics cases, IAXO has the potential to serve as a multi-purpose facility for generic axion and ALP research in the next decade. In this paper we present the conceptual design of IAXO, which follows the layout of an enhanced axion helioscope, based on a purpose-built 20 m-long 8-coils toroidal superconducting magnet. All the eight 60cm-diameter magnet bores are equipped with focusing x-ray optics, able to focus the signal photons into ∼ 0.2 cm2 spots that are imaged by ultra-low-background Micromegas x-ray detectors. The magnet is built into a structure with elevation and azimuth drives that will allow for solar tracking for ∼ 12 h each day.}
}  
  #+end_quote

*** BabyIAXO

- Conceptual Design of BabyIAXO, the intermediate stage towards the
  International Axion Observatory
  *The* main thing to cite for BabyIAXO.
  [[file:~/org/Papers/conceptual_design_babyiaxo_2021_Abeln2021_Article_ConceptualDesignOfBabyIAXOTheI.pdf]]
  #+begin_quote
@article{abeln2021conceptual,
  title={Conceptual Design of BabyIAXO, the intermediate stage towards the International Axion Observatory},
  author={Abeln, A and Altenm{\"u}ller, K and Cuendis, S Arguedas and Armengaud, E and Atti{\'e}, D and Aune, S and Basso, S and Berg{\'e}, L and Biasuzzi, B and De Sousa, PTC Borges and others},
  journal={Journal of High Energy Physics},
  volume={2021},
  number={5},
  pages={1--80},
  year={2021},
  publisher={Springer}
}
  #+end_quote

** Axion models / primakoff flux
- Weighing the solar axion
  Contains, among others, a plot and (newer) description for the solar axion flux (useful as a comparison)
  Φ_P₁₀ = 6.02e10.cm⁻²•s⁻¹•keV⁻¹
  dΦ_a/dE_a = Φ_P₁₀ (g_aγ / 1e-10.GeV⁻¹) * pow(E_a / 1.keV, 2.481) / (exp(E_a / (1.205.keV)))
  [[file:~/org/Papers/Weighing_the_solar_axion.pdf]]
  https://www.researchgate.net/publication/331334319_Weighing_the_solar_axion
  #+begin_quote
@article{weighingSolarAxion,
  author = {Dafni, Theopisti and O'Hare, Ciaran and Lakić, Biljana and Galan, Javier and Iguaz, F. and Irastorza, Igor and Jakovčić, Krešimir and Luzón, G. and Redondo, Javier and Ruiz-Chóliz, Elisa},
  year = {2019},
  month = {02},
  pages = {},
  title = {Weighing the solar axion},
  volume = {99},
  journal = {Physical Review D},
  doi = {10.1103/PhysRevD.99.035037}
}
#+end_quote

** Axion detection  
- Experimental tests of the invisible axion
  1st paper of Sikivie about way to detect axions
  [[file:~/org/Papers/sikivie1983.pdf]]
  #+begin_quote
@article{PhysRevLett.51.1415,
  title = {Experimental Tests of the "Invisible" Axion},
  author = {Sikivie, P.},
  journal = {Phys. Rev. Lett.},
  volume = {51},
  issue = {16},
  pages = {1415--1417},
  numpages = {0},
  year = {1983},
  month = {Oct},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevLett.51.1415},
  url = {https://link.aps.org/doi/10.1103/PhysRevLett.51.1415}
}
  #+end_quote

- Detection rates for invisible axion searches, Sikivie
  2nd paper of Sikive about experiments to detect axions.
  [[file:~/org/Papers/sikivie_1985_detection_rates_PhysRevD.32.2988.pdf]]
  #+begin_quote
@article{PhysRevD.32.2988,
  title = {Detection rates for ``invisible''-axion searches},
  author = {Sikivie, P.},
  journal = {Phys. Rev. D},
  volume = {32},
  issue = {11},
  pages = {2988--2991},
  numpages = {0},
  year = {1985},
  month = {Dec},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevD.32.2988},
  url = {https://link.aps.org/doi/10.1103/PhysRevD.32.2988}
}
  #+end_quote

- An update on the Axion Helioscopes front: current activities at CAST
  and the IAXO project
  Gives an overview over previous helioscopes!
  [[file:~/org/Papers/update_axion_helioscopes_2016.pdf]]
  #+begin_quote
@article{DAFNI2016244,
  title = {An update on the Axion Helioscopes front: current activities at CAST and the IAXO project},
  journal = {Nuclear and Particle Physics Proceedings},
  volume = {273-275},
  pages = {244-249},
  year = {2016},
  note = {37th International Conference on High Energy Physics (ICHEP)},
  issn = {2405-6014},
  doi = {https://doi.org/10.1016/j.nuclphysbps.2015.09.033},
  url = {https://www.sciencedirect.com/science/article/pii/S2405601415005222},
  author = {T. Dafni and M. Arik and E. Armengaud and S. Aune and F.T. Avignone and K. Barth and A. Belov and M. Betz and H. Bräuninger and P. Brax and N. Breijnholt and P. Brun and G. Cantatore and J.M. Carmona and G.P. Carosi and F. Caspers and S. Caspi and S.A. Cetin and D. Chelouche and F.E. Christensen and J.I. Collar and A. Dael and M. Davenport and A.V. Derbin and K. Desch and A. Diago and B. Döbrich and I. Dratchnev and A. Dudarev and C. Eleftheriadis and G. Fanourakis and E. Ferrer-Ribas and P. Friedrich and J. Galán and J.A. García and A. Gardikiotis and J.G. Garza and E.N. Gazis and E. Georgiopoulou and T. Geralis and B. Gimeno and I. Giomataris and S. Gninenko and H. Gómez and D. González-Díaz and E. Gruber and E. Guendelman and T. Guthörl and C.J. Hailey and R. Hartmann and S. Hauf and F. Haug and M.D. Hasinoff and T. Hiramatsu and D.H.H. Hoffmann and D. Horns and F.J. Iguaz and I.G. Irastorza and J. Isern and K. Imai and J. Jacoby and J. Jaeckel and A.C. Jakobsen and K. Jakovčić and J. Kaminski and M. Kawasaki and M. Karuza and K. Königsmann and R. Kotthaus and M. Krčmar and K. Kousouris and C. Krieger and M. Kuster and B. Lakić and J.M. Laurent and O. Limousin and A. Lindner and A. Liolios and A. Ljubičić and G. Luzón and S. Matsuki and V.N. Muratova and S. Neff and T. Niinikoski and C. Nones and I. Ortega and T. Papaevangelou and M.J. Pivovaroff and G. Raffelt and J. Redondo and H. Riege and A. Ringwald and A. Rodríguez and M. Rosu and S. Russenschuck and J. Ruz and K. Saikawa and I. Savvidis and T. Sekiguchi and Y.K. Semertzidis and I. Shilon and P. Sikivie and H. Silva and S.K. Solanki and L. Stewart and H.H.J. {ten Kate} and A. Tomas and S. Troitsky and T. Vafeiadis and K. {van Bibber} and P. Vedrine and J.A. Villar and J.K. Vogel and L. Walckiers and A. Weltman and W. Wester and S.C. Yildiz and K. Zioutas},
  keywords = {axions, dark matter, x-ray detectors, micromegas detectors, x-ray focusing devices, magnet development, CAST, IAXO},
  abstract = {Although they have not yet been detected, axions and axion-like particles (ALPs) continue to maintain the interest (even increasingly so) of the rare-event searches community as viable candidates for the Dark Matter of the Universe but also as a solution for several other puzzles of astrophysics. Their property of coupling to photons has inspired different experimental methods for their detection, one of which is the helioscope technique. The CERN Axion Solar Telescope (CAST) is the most sensitive helioscope built up to date and has recently published part of the latest data taken with the magnet bores gradually filled with 3He, probing the mass range up to 1.17 eV. The International AXion Observatory (IAXO) is being proposed as a facility where different axion studies can be performed, with the primary goal to study axions coming from the Sun. Designed to maximize sensitivity, it will improve the levels reached by CAST by almost 5 orders of magnitude in signal detection, that is more than one order of magnitude in terms of gaγ. Here we will summarize the most important aspects of the helioscopes, and focus mainly on IAXO, based on the recent papers [1, 2].}
}  
  #+end_quote

** Other axion helioscopes

*** Rochester-Brookhaven-Florida

- Design for a practical laboratory detector for solar axions
  Paper about the first axion helioscope.
  [[file:~/org/Papers/design_practical_lab_detection_solar_axions_brookhaven_PhysRevD.39.2089.pdf]]
#+begin_quote
@article{PhysRevD.39.2089,
  title = {Design for a practical laboratory detector for solar axions},
  author = {van Bibber, K. and McIntyre, P. M. and Morris, D. E. and Raffelt, G. G.},
  journal = {Phys. Rev. D},
  volume = {39},
  issue = {8},
  pages = {2089--2099},
  numpages = {0},
  year = {1989},
  month = {Apr},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevD.39.2089},
  url = {https://link.aps.org/doi/10.1103/PhysRevD.39.2089}
}
#+end_quote
- Search for solar axions
  2nd paper about the first axion helioscope
  [[file:~/org/Papers/search_for_solar_axions_brookhaven_PhysRevLett.69.2333.pdf]]
#+begin_quote
@article{PhysRevLett.69.2333,
  title = {Search for solar axions},
  author = {Lazarus, D. M. and Smith, G. C. and Cameron, R. and Melissinos, A. C. and Ruoso, G. and Semertzidis, Y. K. and Nezrick, F. A.},
  journal = {Phys. Rev. Lett.},
  volume = {69},
  issue = {16},
  pages = {2333--2336},
  numpages = {0},
  year = {1992},
  month = {Oct},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevLett.69.2333},
  url = {https://link.aps.org/doi/10.1103/PhysRevLett.69.2333}
}
#+end_quote

*** SUMICO

- Direct search for solar axions by using strong magnetic field and
  X-ray detectors
  1st paper about SUMICO.
  [[file:~/org/Papers/sumico_paper_direct_search_for_solar_axions_1998_s0370.pdf]]
  #+begin_quote
@article{MORIYAMA1998147,
  title = {Direct search for solar axions by using strong magnetic field and X-ray detectors},
  journal = {Physics Letters B},
  volume = {434},
  number = {1},
  pages = {147-152},
  year = {1998},
  issn = {0370-2693},
  doi = {https://doi.org/10.1016/S0370-2693(98)00766-7},
  url = {https://www.sciencedirect.com/science/article/pii/S0370269398007667},
  author = {Shigetaka Moriyama and Makoto Minowa and Toshio Namba and Yoshizumi Inoue and Yuko Takasu and Akira Yamamoto},
  keywords = {Axion, Solar core, PIN photodiode, X-ray detector, Superconducting magnet, Nambu-Goldstone boson},
  abstract = {We have searched for axions which could be produced in the solar core by exploiting their conversion to X rays in a strong laboratory magnetic field. The signature of the solar axion is an increase in the rate of the X rays detected in a magnetic helioscope when the sun is within its acceptance. From the absence of such a signal we set a 95% confidence level limit on the axion coupling to two photons gaγγ≡1/M<6.0×10−10GeV−1, provided the axion mass ma<0.03eV. The limit on the coupling is factor 4.5 more stringent than the recent experimental result. This is the first experiment whose sensitivity to gaγγ is higher than the limit constrained by the solar age consideration.}
}
  #+end_quote

- Search for sub-electronvolt solar axions using coherent conversion
  of axions into photons in magnetic field and gas helium
  2nd paper about SUMICO.
  [[file:~/org/Papers/sumico_2_search_for_sub_ev_solar_axions_2002.pdf]]
  #+begin_quote
@article{INOUE200218,
  title = {Search for sub-electronvolt solar axions using coherent conversion of axions into photons in magnetic field and gas helium},
  journal = {Physics Letters B},
  volume = {536},
  number = {1},
  pages = {18-23},
  year = {2002},
  issn = {0370-2693},
  doi = {https://doi.org/10.1016/S0370-2693(02)01822-1},
  url = {https://www.sciencedirect.com/science/article/pii/S0370269302018221},
  author = {Yoshizumi Inoue and Toshio Namba and Shigetaka Moriyama and Makoto Minowa and Yuko Takasu and Takashi Horiuchi and Akira Yamamoto},
  keywords = {Solar axion, Helioscope, PIN photodiode, Superconducting magnet},
  abstract = {A search for solar axions has been performed using an axion helioscope which is equipped with a 2.3-m long 4T superconducting magnet, PIN-photodiode X-ray detectors, and a telescope mount mechanism to track the sun. In addition, a gas container to hold dispersion-matching gas has been developed and a mass region up to ma=0.27eV was newly explored. From the absence of any evidence, analysis sets a limit on axion–photon coupling constant to be gaγγ<6.8–10.9×10−10GeV−1 for the axion mass of 0.05<ma<0.27eV at 95% confidence level, which is more stringent than the limit inferred from the solar-age consideration. This result gives currently the most stringent observational limit on the existence of solar axions in this mass region.}
}
  #+end_quote

- Search for solar axions with mass around 1 eV using coherent
  conversion of axions into photons
  3rd SUMICO paper.
  [[file:~/org/Papers/sumico_3_search_for_solar_axions_1ev_2008j.physletb.2008.08.020.pdf]]
  #+begin_quote
@article{INOUE200893,
  title = {Search for solar axions with mass around 1 eV using coherent conversion of axions into photons},
  journal = {Physics Letters B},
  volume = {668},
  number = {2},
  pages = {93-97},
  year = {2008},
  issn = {0370-2693},
  doi = {https://doi.org/10.1016/j.physletb.2008.08.020},
  url = {https://www.sciencedirect.com/science/article/pii/S0370269308010137},
  author = {Y. Inoue and Y. Akimoto and R. Ohta and T. Mizumoto and A. Yamamoto and M. Minowa},
  keywords = {Solar axion, Helioscope, PIN photodiode, Superconducting magnet},
  abstract = {A search for solar axions has been performed using an axion helioscope which is equipped with a 2.3-m long 4 T superconducting magnet, a gas container to hold dispersion-matching gas, PIN-photodiode X-ray detectors, and a telescope mount mechanism to track the sun. A mass region around ma=1 eV was newly explored. From the absence of any evidence, analysis sets a limit on axion–photon coupling constant to be gaγγ<5.6–13.4×10−10 GeV−1 for the axion mass of 0.84<ma<1.00 eV at 95% confidence level. It is the first result to search for the axion in the gaγγ–ma parameter region of the preferred axion models with a magnetic helioscope.}
}
  #+end_quote


** Talks

Igor talk at ICPP 2011:
https://indico.cern.ch/event/117804/contributions/1330107/attachments/58112/83695/Irastorza_ICPP2011.pdf
contains some historic stuff about axion searches


* Detectors

** Gaseous detector physics

- A method to improve tracking and particle identification in TPCs and
  silicon detectors
  Paper that talks about mean vs most probable energy loss from
  Landau, deviation from Landau in energy loss etc. in TPCs
  [[file:~/org/Papers/gaseous_detectors_energy_loss_tpcs_bichsel2006.pdf]]
  #+begin_quote
@article{BICHSEL2006154,
  title = {A method to improve tracking and particle identification in TPCs and silicon detectors},
  journal = {Nuclear Instruments and Methods in Physics Research Section A: Accelerators, Spectrometers, Detectors and Associated Equipment},
  volume = {562},
  number = {1},
  pages = {154-197},
  year = {2006},
  issn = {0168-9002},
  doi = {https://doi.org/10.1016/j.nima.2006.03.009},
  url = {https://www.sciencedirect.com/science/article/pii/S0168900206005353},
  author = {Hans Bichsel},
  keywords = {Energy loss, Ionization, Particle identification, Tracking},
  abstract = {The measurement of the ionization by charged particles in a medium (gas or condensed) together with the measurement of their momentum or energy is used for tracking the particles and to determine their identity. For tracking the lateral extent of the ionization cloud should be known. For tracking and for charged particle identification (PID), one must understand that energy loss of particles, ionization and detector output are related, but not identical. In this paper, I discuss the relevant physics processes involved in PID and tracking and the stochastic nature of the energy loss mechanism. These calculations can be made with analytic and Monte Carlo methods. The expression dE/dx should be abandoned; it is never relevant to the signals in a particle-by-particle analysis. Specific terms such as energy loss, energy deposition, ionization and pulse height should be used instead. It is important that an accurate data analysis requires attention to track segmentation. I will show that properties of straggling functions for gases and thin silicon detectors are similar for equivalent absorber thicknesses and general conclusions given for one absorber will be valid for others. Thus, these techniques can be used in Time Projection Chambers (TPCs) and Silicon Drift Detectors. I will show how to use this formalism in the STAR and ALICE TPCs and describe how its use has improved the performance of the detector.}
}  
  #+end_quote
