
* Axions

** CAST
- A decommissioned LHC model magnet as an axion telescope
  CAST proposal
  [[file:~/org/Papers/cast_proposal_decomissioned_lhc_magnet_1999.pdf]]
  #+begin_src latex :tangle references.bib
@article{ZIOUTAS1999480,
  title = {A decommissioned LHC model magnet as an axion telescope},
  journal = {Nuclear Instruments and Methods in Physics Research Section A: Accelerators, Spectrometers, Detectors and Associated Equipment},
  volume = {425},
  number = {3},
  pages = {480-487},
  year = {1999},
  issn = {0168-9002},
  doi = {https://doi.org/10.1016/S0168-9002(98)01442-9},
  url = {https://www.sciencedirect.com/science/article/pii/S0168900298014429},
  author = {K. Zioutas and C.E. Aalseth and D. Abriola and F.T.Avignone III and R.L. Brodzinski and J.I. Collar and R. Creswick and D.E.Di Gregorio and H. Farach and A.O. Gattone and C.K. Guérard and F. Hasenbalg and M. Hasinoff and H. Huck and A. Liolios and H.S. Miley and A. Morales and J. Morales and D. Nikas and S. Nussinov and A. Ortiz and E. Savvidis and S. Scopel and P. Sievers and J.A. Villar and L. Walckiers},
  keywords = {Solar axions, LHC, Superconducting magnets, Dark matter}
}  
  #+end_src

- First Results from the CERN Axion Solar Telescope
  Contains, among others, an analytical expression for the solar
  axion flux:
  g₁₀ = g_aγ • 10¹⁰ GeV
  dΦ_a/dE_a = g²₁₀ 3.821•10¹⁰ cm⁻²•s⁻¹•keV⁻¹ (E_a / keV)³ / (exp(E_a / (1.103 keV)) - 1)
  results in an integrated flux:
  Φ_a = g²₁₀ 3.67•10¹¹ cm⁻²•s⁻¹
  - https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.94.121301
  - [[file:~/org/Papers/first_cast_results_physrevlett.94.121301.pdf]]
  #+begin_src latex :tangle references.bib
@article{PhysRevLett.94.121301,
  title = {First Results from the CERN Axion Solar Telescope},
  author = {Zioutas, K. and Andriamonje, S. and Arsov, V. and Aune, S. and Autiero, D. and Avignone, F. T. and Barth, K. and Belov, A. and Beltr\'an, B. and Br\"auninger, H. and Carmona, J. M. and Cebri\'an, S. and Chesi, E. and Collar, J. I. and Creswick, R. and Dafni, T. and Davenport, M. and Di Lella, L. and Eleftheriadis, C. and Englhauser, J. and Fanourakis, G. and Farach, H. and Ferrer, E. and Fischer, H. and Franz, J. and Friedrich, P. and Geralis, T. and Giomataris, I. and Gninenko, S. and Goloubev, N. and Hasinoff, M. D. and Heinsius, F. H. and Hoffmann, D. H. H. and Irastorza, I. G. and Jacoby, J. and Kang, D. and K\"onigsmann, K. and Kotthaus, R. and Kr\ifmmode \check{c}\else \v{c}\fi{}mar, M. and Kousouris, K. and Kuster, M. and Laki\ifmmode \acute{c}\else \'{c}\fi{}, B. and Lasseur, C. and Liolios, A. and Ljubi\ifmmode \check{c}\else \v{c}\fi{}i\ifmmode \acute{c}\else \'{c}\fi{}, A. and Lutz, G. and Luz\'on, G. and Miller, D. W. and Morales, A. and Morales, J. and Mutterer, M. and Nikolaidis, A. and Ortiz, A. and Papaevangelou, T. and Placci, A. and Raffelt, G. and Ruz, J. and Riege, H. and Sarsa, M. L. and Savvidis, I. and Serber, W. and Serpico, P. and Semertzidis, Y. and Stewart, L. and Vieira, J. D. and Villar, J. and Walckiers, L. and Zachariadou, K.},
  collaboration = {CAST Collaboration},
  journal = {Phys. Rev. Lett.},
  volume = {94},
  issue = {12},
  pages = {121301},
  numpages = {5},
  year = {2005},
  month = {Apr},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevLett.94.121301},
  url = {https://link.aps.org/doi/10.1103/PhysRevLett.94.121301}
}
#+end_src

- An improved limit on the axion–photon coupling from the CAST
  experiment
  Full results of phase I at CAST
  Contains a good overview on how to get from solar physics to axion
  flux!!
  Contains information about the log likelihood method that (I think)
  is mostly the same as the 2013 axion-electron paper.
  [[file:~/org/Papers/cast_phase_I_results_andriamonje2007.pdf]]
  #+begin_src latex :tangle references.bib
@article{Andriamonje_2007,
	doi = {10.1088/1475-7516/2007/04/010},
	url = {https://doi.org/10.1088/1475-7516/2007/04/010},
	year = 2007,
	month = {apr},
	publisher = {{IOP} Publishing},
	volume = {2007},
	number = {04},
	pages = {010--010},
	author = {S Andriamonje and S Aune and D Autiero and K Barth and A Belov and B Beltr{\'{a}}n and H Bräuninger and J M Carmona and S Cebri{\'{a}}n and J I Collar and T Dafni and M Davenport and L Di Lella and C Eleftheriadis and J Englhauser and G Fanourakis and E Ferrer Ribas and H Fischer and J Franz and P Friedrich and T Geralis and I Giomataris and S Gninenko and H G{\'{o}}mez and M Hasinoff and F H Heinsius and D H H Hoffmann and I G Irastorza and J Jacoby and K Jakov{\v{c}}i{\'{c}} and D Kang and K Königsmann and R Kotthaus and M Kr{\v{c}}mar and K Kousouris and M Kuster and B Laki{\'{c}} and C Lasseur and A Liolios and A Ljubi{\v{c}}i{\'{c}} and G Lutz and G Luz{\'{o}}n and D Miller and A Morales and J Morales and A Ortiz and T Papaevangelou and A Placci and G Raffelt and H Riege and A Rodr{\'{\i}}guez and J Ruz and I Savvidis and Y Semertzidis and P Serpico and L Stewart and J Vieira and J Villar and J Vogel and L Walckiers and K Zioutas and CAST Collaboration},
	title = {An improved limit on the axion{\textendash}photon coupling from the {CAST} experiment},
	journal = {Journal of Cosmology and Astroparticle Physics}
}  
  #+end_src

- Probing the eV-scale axions with CAST
  Contains first results of CAST phase II. 4He 2005 to 2007, then 3He
  results in 2008 (continued on until 2011, other paper below).
  [[file:~/org/Papers/probing_ev_scale_axions_cast_E._Arik_2009_J._Cosmol._Astropart._Phys._2009_008.pdf]]
  #+begin_src latex :tangle references.bib
@article{Arik_2009,
	doi = {10.1088/1475-7516/2009/02/008},
	url = {https://doi.org/10.1088/1475-7516/2009/02/008},
	year = 2009,
	month = {feb},
	publisher = {{IOP} Publishing},
	volume = {2009},
	number = {02},
	pages = {008--008},
	author = {E Arik and S Aune and D Autiero and K Barth and A Belov and B Beltr{\'{a}}n and S Borghi and G Bourlis and F.S Boydag and H Bräuninger and J.M Carmona and S Cebri{\'{a}}n and S.A Cetin and J.I Collar and T Dafni and M Davenport and L. Di Lella and O.B Dogan and C Eleftheriadis and N Elias and G Fanourakis and E Ferrer-Ribas and H Fischer and P Friedrich and J Franz and J Gal{\'{a}}n and T Geralis and I Giomataris and S Gninenko and H G{\'{o}}mez and R Hartmann and M Hasinoff and F.H Heinsius and I Hikmet and D.H.H Hoffmann and I.G Irastorza and J Jacoby and K Jakov{\v{c}}i{\'{c}} and D Kang and K Königsmann and R Kotthaus and M Kr{\v{c}}mar and K Kousouris and M Kuster and B Laki{\'{c}} and C Lasseur and A Liolios and A Ljubi{\v{c}}i{\'{c}} and G Lutz and G Luz{\'{o}}n and D Miller and J Morales and T Niinikoski and A Nordt and A Ortiz and T Papaevangelou and M.J Pivovaroff and A Placci and G Raffelt and H Riege and A Rodr{\'{\i}}guez and J Ruz and I Savvidis and Y Semertzidis and P Serpico and R Soufli and L Stewart and K. van Bibber and J Villar and J Vogel and L Walckiers and K Zioutas},
	title = {Probing {eV}-scale axions with {CAST}},
	journal = {Journal of Cosmology and Astroparticle Physics}
}  
  #+end_src

- New solar axion search using the CERN Axion Solar Telescope with $^{4}\mathrm{He}$ filling
  Contains overview of 4He (the first) and 3He buffer gas data
  takings.
  Contains information about unbinned log likelihood method also used
  in nature paper!
  [[file:~/org/Papers/new_solar_axion_search_cast_4he_2015_PhysRevD.92.021101.pdf]]
  #+begin_src latex :tangle references.bib
@article{PhysRevD.92.021101,
  title = {New solar axion search using the CERN Axion Solar Telescope with $^{4}\mathrm{He}$ filling},
  author = {Arik, M. and Aune, S. and Barth, K. and Belov, A. and Br\"auninger, H. and Bremer, J. and Burwitz, V. and Cantatore, G. and Carmona, J. M. and Cetin, S. A. and Collar, J. I. and Da Riva, E. and Dafni, T. and Davenport, M. and Dermenev, A. and Eleftheriadis, C. and Elias, N. and Fanourakis, G. and Ferrer-Ribas, E. and Gal\'an, J. and Garc\'{\i}a, J. A. and Gardikiotis, A. and Garza, J. G. and Gazis, E. N. and Geralis, T. and Georgiopoulou, E. and Giomataris, I. and Gninenko, S. and G\'omez Marzoa, M. and Hasinoff, M. D. and Hoffmann, D. H. H. and Iguaz, F. J. and Irastorza, I. G. and Jacoby, J. and Jakov\ifmmode \check{c}\else \v{c}\fi{}i\ifmmode \acute{c}\else \'{c}\fi{}, K. and Karuza, M. and Kavuk, M. and Kr\ifmmode \check{c}\else \v{c}\fi{}mar, M. and Kuster, M. and Laki\ifmmode \acute{c}\else \'{c}\fi{}, B. and Laurent, J. M. and Liolios, A. and Ljubi\ifmmode \check{c}\else \v{c}\fi{}i\ifmmode \acute{c}\else \'{c}\fi{}, A. and Luz\'on, G. and Neff, S. and Niinikoski, T. and Nordt, A. and Ortega, I. and Papaevangelou, T. and Pivovaroff, M. J. and Raffelt, G. and Rodr\'{\i}guez, A. and Rosu, M. and Ruz, J. and Savvidis, I. and Shilon, I. and Solanki, S. K. and Stewart, L. and Tom\'as, A. and Vafeiadis, T. and Villar, J. and Vogel, J. K. and Yildiz, S. C. and Zioutas, K.},
  collaboration = {CAST Collaboration},
  journal = {Phys. Rev. D},
  volume = {92},
  issue = {2},
  pages = {021101},
  numpages = {6},
  year = {2015},
  month = {Jul},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevD.92.021101},
  url = {https://link.aps.org/doi/10.1103/PhysRevD.92.021101}
}
  #+end_src

** g_ae - Axion electron limits

- CAST constraints on the axion-electron coupling
  The paper from 2013 about the axion electron coupling.
  [[file:~/org/Papers/cast_axion_electron_jcap_2013_pnCCD.pdf]]
  #+begin_src latex :tangle references.bib
@article{Barth_2013,
	doi = {10.1088/1475-7516/2013/05/010},
	url = {https://doi.org/10.1088/1475-7516/2013/05/010},
	year = 2013,
	month = {may},
	publisher = {{IOP} Publishing},
	volume = {2013},
	number = {05},
	pages = {010--010},
	author = {K Barth and A Belov and B Beltran and H Bräuninger and J.M Carmona and J.I Collar and T Dafni and M Davenport and L. Di Lella and C Eleftheriadis and J Englhauser and G Fanourakis and E Ferrer-Ribas and H Fischer and J Franz and P Friedrich and J Gal{\'{a}}n and J.A Garc{\'{\i}}a and T Geralis and I Giomataris and S Gninenko and H G{\'{o}}mez and M.D Hasinoff and F.H Heinsius and D.H.H Hoffmann and I.G Irastorza and J Jacoby and K Jakov{\v{c}}i{\'{c}} and D Kang and K Königsmann and R Kotthaus and K Kousouris and M Kr{\v{c}}mar and M Kuster and B Laki{\'{c}} and A Liolios and A Ljubi{\v{c}}i{\'{c}} and G Lutz and G Luz{\'{o}}n and D.W Miller and T Papaevangelou and M.J Pivovaroff and G Raffelt and J Redondo and H Riege and A Rodr{\'{\i}}guez and J Ruz and I Savvidis and Y Semertzidis and L Stewart and K. Van Bibber and J.D Vieira and J.A Villar and J.K Vogel and L Walckiers and K Zioutas},
	title = {{CAST} constraints on the axion-electron coupling},
	journal = {Journal of Cosmology and Astroparticle Physics}
}
  #+end_src

- Solar axion flux from the axion-electron coupling
  The accompanying theory paper about the solar axion-electron flux
  [[file:~/org/Papers/solar_axion_electron_flux_redondo2013.pdf]]
  #+begin_src latex :tangle references.bib
@article{Redondo_2013,
	doi = {10.1088/1475-7516/2013/12/008},
	url = {https://doi.org/10.1088/1475-7516/2013/12/008},
	year = 2013,
	month = {dec},
	publisher = {{IOP} Publishing},
	volume = {2013},
	number = {12},
	pages = {008--008},
	author = {Javier Redondo},
	title = {Solar axion flux from the axion-electron coupling},
	journal = {Journal of Cosmology and Astroparticle Physics}
}
  #+end_src

** g_aγ - Axion photon limits

- New CAST limit on the axion--photon interaction
  CAST nature paper.
  [[file:~/org/Papers/nature_cast_limit_axion_photon_nphys4109.pdf]]
  #+begin_src latex :tangle references.bib
@article{cast_nature,
  title={New CAST limit on the axion--photon interaction},
  author={Collaboration, CAST and others},
  journal={Nature Physics},
  volume={13},
  pages={584--590},
  url={https://www.nature.com/articles/nphys4109},
  year={2017}
}
  #+end_src


** β_γ - Chameleon limits

- Search for solar chameleons with an InGrid based X-ray detector at the CAST experiment
  #+begin_src latex :tangle references.bib
@article{krieger2018search,
  title={Search for solar chameleons with an InGrid based X-ray detector at the CAST experiment},
  author={Krieger, Christoph},
  year={2018},
  publisher={Universit{\"a}ts-und Landesbibliothek Bonn}
}
  #+end_src

  
  
*** Telescopes

- Spiegelsysteme streifenden Einfalls als abbildende Optiken für
  Röntgenstrahlen
  The paper by Hans Wolter introducing the I type X-ray optics
  [[file:~/org/Papers/wolter_type_1_1952_andp.19524450108.pdf]]
  #+begin_src latex :tangle references.bib
@article{wolter_1_type,
  author = {Wolter, Hans},
  title = {Spiegelsysteme streifenden Einfalls als abbildende Optiken für Röntgenstrahlen},
  journal = {Annalen der Physik},
  volume = {445},
  number = {1-2},
  pages = {94-114},
  doi = {https://doi.org/10.1002/andp.19524450108},
  url = {https://onlinelibrary.wiley.com/doi/abs/10.1002/andp.19524450108},
  eprint = {https://onlinelibrary.wiley.com/doi/pdf/10.1002/andp.19524450108},
  year = {1952}
}
  #+end_src

- Conical imaging mirrors for high-speed x-ray telescopes
  Apparently a paper that expands on the Wolter paper for actual
  applications by using a conical design?
  [[file:~/org/Papers/conical_xray_telescopes_petre1985.pdf]]
  #+begin_src latex :tangle references.bib
@article{Petre:85,
  oauthor = {Robert Petre and Peter J. Serlemitsos},
  journal = {Appl. Opt.},
  keywords = {Optical systems; Radiation detectors; Spatial resolution; X ray imaging; X ray mirrors; X ray telescopes},
  number = {12},
  pages = {1833--1837},
  publisher = {OSA},
  title = {Conical imaging mirrors for high-speed x-ray telescopes},
  volume = {24},
  month = {Jun},
  year = {1985},
  url = {http://ao.osa.org/abstract.cfm?URI=ao-24-12-1833},
  doi = {10.1364/AO.24.001833}
}
  #+end_src
  

**** ABRIXAS

- The x-ray telescope of CAST
  [[~/org/Papers/cast_xray_telescope_abrixas_Kuster_2007_New_J._Phys._9_169.pdf]]
  #+begin_src latex :tangle references.bib
@article{CAST_telescope_ccd,
  author={M Kuster and H Bräuninger and S Cebrián and M Davenport and C Eleftheriadis and J Englhauser and H Fischer and J Franz and P
Friedrich and R Hartmann and F H Heinsius and D H H Hoffmann and G Hoffmeister and J N Joux and D Kang and K Königsmann and R
Kotthaus and T Papaevangelou and C Lasseur and A Lippitsch and G Lutz and J Morales and A Rodríguez and L Strüder and J Vogel and 
Zioutas},
  title={The x-ray telescope of CAST},
  journal={New Journal of Physics},
  volume={9},
  number={6},
  pages={169},
  url={http://stacks.iop.org/1367-2630/9/i=6/a=169},
  year={2007},
}
  #+end_src

- ABRIXAS: an imaging x-ray survey in the 0.5- to 10-keV range
  Details about the ABRIXAS X-ray telescope
  [[file:~/org/Papers/abrixas_telescope_mpe_cast_12.331248.pdf]]  
  #+begin_src latex :tangle references.bib
@inproceedings{ABRIXAS_0,
  author = {Peter Friedrich},
  title = {{ABRIXAS: an imaging x-ray survey in the 0.5- to 10-keV range}},
  volume = {3444},
  booktitle = {X-Ray Optics, Instruments, and Missions},
  editor = {Richard B. Hoover and Arthur B. C. Walker II},
  organization = {International Society for Optics and Photonics},
  publisher = {SPIE},
  pages = {342 -- 349},
  year = {1998},
  doi = {},
  URL = {https://doi.org/10.1117/12.331248}
}

@article{article,
  author = {Friedrich, P. and Hasinger, Gunther and Richter, G. and Fritze, K. and Trümper, J. and Bräuninger, H. and Predehl, P. and Staubert, Ruediger and Kendziorra, E.},
  year = {1996},
  month = {01},
  pages = {681-682},
  title = {ABRIXAS, an imaging telescope for a 0.5-10 keV survey.},
  volume = {-1}
}
  #+end_src

- Mirror system for the German x-ray satellite ABRIXAS: I. Flight
  mirror fabrication, integration, and testing
  [[file:~/org/Papers/abrixas_mirror_system_integration_testing_1998_12.331249.pdf]]
  #+begin_src latex :tangle references.bib
@inproceedings{ABRIXAS_1,
  author = {Juergen Altmann and Wilhelm J. Egle and Ulrich Bingel and Wolfgang Hafner and Bernhard Gaenswein and Herbert Schwarz and Anton Neugschwender},
  title = {{Mirror system for the German x-ray satellite ABRIXAS: I. Flight mirror fabrication, integration, and testing}},
  volume = {3444},
  booktitle = {X-Ray Optics, Instruments, and Missions},
  editor = {Richard B. Hoover and Arthur B. C. Walker II},
  organization = {International Society for Optics and Photonics},
  publisher = {SPIE},
  pages = {350 -- 358},
  year = {1998},
  doi = {},
  URL = {https://doi.org/10.1117/12.331249}
}
  #+end_src

- Mirror system for the German x-ray satellite ABRIXAS: II. Design and
  mirror development
  [[file:~/org/Papers/abrixas_mirror_system_design_development_12.331250.pdf]]
  #+begin_src latex :tangle references.bib
@inproceedings{ABRIXAS_2,
  author = {Wilhelm J. Egle and Juergen Altmann and Paul Kaufmann and Hartmut Muenker and Gerhard Derst and Herbert Schwarz and Anton Neugschwender},
  title = {{Mirror system for the German x-ray satellite ABRIXAS: II. Design and mirror development}},
  volume = {3444},
  booktitle = {X-Ray Optics, Instruments, and Missions},
  editor = {Richard B. Hoover and Arthur B. C. Walker II},
  organization = {International Society for Optics and Photonics},
  publisher = {SPIE},
  pages = {359 -- 368},
  year = {1998},
  doi = {},
  URL = {https://doi.org/10.1117/12.331250}
}
  #+end_src

**** LLNL telescope

- X-ray optics in new instruments for astro- and astroparticle physics
  The PhD thesis that studied the optimizations for the LLNL telescope
  [[file:~/org/Papers/llnl_telescope_optimizations_phdthesis_for_DTU_orbit.pdf]]
  #+begin_src latex :tangle references.bib
@phdthesis{9d8b4de98f0542e9bbe71fe572f3d3f5,
  title = "X-ray optics in new instruments for astro- and astroparticle physics",
  author = "Jakobsen, {Anders Clemen}",
  year = "2015",
  language = "English",
  isbn = "978-87-91694-28-8",
  publisher = "DTU Space",
}
  #+end_src

- A Micromegas-based low-background x-ray detector coupled to a slumped-glass telescope for axion research
  First paper publishing results using the LLNL telesope at CAST
  [[file:~/org/Papers/llnl_telescope_cast_mm_1509_06190.pdf]]
  #+begin_src latex :tangle references.bib
@article{llnl_telescope_first_cast_results,
  author = {Aznar, Francisco and Castel, Juan Francisco and Christensen, FE and Dafni, Theopisti and Decker, Todd and Ferrer Ribas, Esther and Garcia, J. and Giomataris, Ioannis and Garza, J. and Hailey, CJ},
  year = {2015},
  month = {01},
  pages = {008},
  title = {A Micromegas-based low-background x-ray detector coupled to a slumped-glass telescope for axion research},
  volume = {2015},
  journal = {Journal of Cosmology and Astroparticle Physics}
} 
  #+end_src

***** Nustar

- THE NUCLEAR SPECTROSCOPIC TELESCOPE ARRAY (NuSTAR) HIGH-ENERGY X-RAY
  MISSION
  Paper introducing the NuStar mission
  [[file:~/org/Papers/nustar_introduction_Harrison_2013_ApJ_770_103.pdf]]
  #+begin_src latex :tangle references.bib
@article{Harrison_2013,
	doi = {10.1088/0004-637x/770/2/103},
	url = {https://doi.org/10.1088/0004-637x/770/2/103},
	year = 2013,
	month = {may},
	publisher = {American Astronomical Society},
	volume = {770},
	number = {2},
	pages = {103},
	author = {Fiona A. Harrison and William W. Craig and Finn E. Christensen and Charles J. Hailey and William W. Zhang and Steven E. Boggs and Daniel Stern and W. Rick Cook and Karl Forster and Paolo Giommi and Brian W. Grefenstette and Yunjin Kim and Takao Kitaguchi and Jason E. Koglin and Kristin K. Madsen and Peter H. Mao and Hiromasa Miyasaka and Kaya Mori and Matteo Perri and Michael J. Pivovaroff and Simonetta Puccetti and Vikram R. Rana and Niels J. Westergaard and Jason Willis and Andreas Zoglauer and Hongjun An and Matteo Bachetti and Nicolas M. Barri{\`{e}}re and Eric C. Bellm and Varun Bhalerao and Nicolai F. Brejnholt and Felix Fuerst and Carl C. Liebe and Craig B. Markwardt and Melania Nynka and Julia K. Vogel and Dominic J. Walton and Daniel R. Wik and David M. Alexander and Lynn R. Cominsky and Ann E. Hornschemeier and Allan Hornstrup and Victoria M. Kaspi and Greg M. Madejski and Giorgio Matt and Silvano Molendi and David M. Smith and John A. Tomsick and Marco Ajello and David R. Ballantyne and Mislav Balokovi{\'{c}} and Didier Barret and Franz E. Bauer and Roger D. Blandford and W. Niel Brandt and Laura W. Brenneman and James Chiang and Deepto Chakrabarty and Jerome Chenevez and Andrea Comastri and Francois Dufour and Martin Elvis and Andrew C. Fabian and Duncan Farrah and Chris L. Fryer and Eric V. Gotthelf and Jonathan E. Grindlay and David J. Helfand and Roman Krivonos and David L. Meier and Jon M. Miller and Lorenzo Natalucci and Patrick Ogle and Eran O. Ofek and Andrew Ptak and Stephen P. Reynolds and Jane R. Rigby and Gianpiero Tagliaferri and Stephen E. Thorsett and Ezequiel Treister and C. Megan Urry},
	title = {{THENUCLEAR} {SPECTROSCOPIC} {TELESCOPE} {ARRAY}({NuSTAR}) {HIGH}-{ENERGY} X-{RAY} {MISSION}},
	journal = {The Astrophysical Journal}
}  
  #+end_src

- Development of the HEFT and NuSTAR focusing telescopes
  1st paper introducing techniques used for nustar
  [[file:~/org/Papers/development_nustar_focusing_telescope_harrison2006.pdf]]
  #+begin_src latex :tangle references.bib
@Inbook{Harrison2006,
  author="Harrison, Fiona A.
  and Christensen, Finn E.
  and Craig, William
  and Hailey, Charles
  and Baumgartner, Wayne
  and Chen, C. M. H.
  and Chonko, James
  and Cook, W. Rick
  and Koglin, Jason
  and Madsen, Kristin-Kruse
  and Pivavoroff, Michael
  and Boggs, Steven
  and Smith, David",
  editor="von Ballmoos, Peter",
  title="Development of the HEFT and NuSTAR focusing telescopes",
  bookTitle="Focusing Telescopes in Nuclear Astrophysics",
  year="2006",
  publisher="Springer Netherlands",
  address="Dordrecht",
  pages="131--137",
  isbn="978-1-4020-5304-7",
  doi="10.1007/978-1-4020-5304-7_15",
  url="https://doi.org/10.1007/978-1-4020-5304-7_15"
}
  #+end_src

- NuSTAR hard x-ray optics design and performance
  2nd paper introducing techniques used in Nustar telescope
  [[file:~/org/Papers/nustar_optics_design_performance_koglin2009.pdf]]
  #+begin_src latex :tangle references.bib
@inproceedings{nustar_design_performance,
  author = {Jason E. Koglin and HongJun An and Kenneth L. Blaedel and Nicolai F. Brejnholt and Finn E. Christensen and William W. Craig and Todd A. Decker and Charles J. Hailey and Layton C. Hale and Fiona A. Harrison and Carsten P. Jensen and Kristin K. Madsen and Kaya Mori and Michael J. Pivovaroff and Gordon Tajiri and William W. Zhang},
  title = {{NuSTAR hard x-ray optics design and performance}},
  volume = {7437},
  booktitle = {Optics for EUV, X-Ray, and Gamma-Ray Astronomy IV},
  editor = {Stephen L. O'Dell and Giovanni Pareschi},
  organization = {International Society for Optics and Photonics},
  publisher = {SPIE},
  pages = {107 -- 114},
  keywords = {Hard X-ray telescope, X-ray optics, segmented glass, NuSTAR},
  year = {2009},
  doi = {},
  URL = {https://doi.org/10.1117/12.826724}
}
  #+end_src

- Fabrication of the NuSTAR flight optics
  3rd paper introducing techniques used for nustar telescope
  [[file:~/org/Papers/nustar_fabrication_craig2011.pdf]]
  #+begin_src latex :tangle references.bib
@inproceedings{nustar_fabrication,
  author = {William W. Craig and HongJun An and Kenneth L. Blaedel and Finn E. Christensen and Todd A. Decker and Anne Fabricant and Jeff Gum and Charles J. Hailey and Layton Hale and Carsten B. Jensen and Jason E. Koglin and Kaya Mori and Melanie Nynka and Michael J. Pivovaroff and Marton V. Sharpe and Marcela Stern and Gordon Tajiri and William W. Zhang},
  title = {{Fabrication of the NuSTAR flight optics}},
  volume = {8147},
  booktitle = {Optics for EUV, X-Ray, and Gamma-Ray Astronomy V},
  editor = {Stephen L. O'Dell and Giovanni Pareschi},
  organization = {International Society for Optics and Photonics},
  publisher = {SPIE},
  pages = {151 -- 164},
  keywords = {Hard X-ray telescope, X-ray optics, NuSTAR, thermally-slumped glass},
  year = {2011},
  doi = {},
  URL = {https://doi.org/10.1117/12.895278}
}
  #+end_src

- The Nuclear Spectroscopic Telescope Array (NuSTAR): optics overview
  and current status
  4th paper introducing nustar telescope
  [[file:~/org/Papers/nustar_overview_status_hailey2010.pdf]]
  #+begin_src latex :tangle references.bib
@inproceedings{nustar_overview_status,
  author = {Charles J. Hailey and HongJun An and Kenneth L. Blaedel and Nicolai F. Brejnholt and Finn E. Christensen and William W. Craig and Todd A. Decker and Melanie Doll and Jeff Gum and Jason E. Koglin and Carsten P. Jensen and Layton Hale and Kaya Mori and Michael J. Pivovaroff and Marton Sharpe and Marcela Stern and Gordon Tajiri and William W. Zhang},
  title = {{The Nuclear Spectroscopic Telescope Array (NuSTAR): optics overview and current status}},
  volume = {7732},
  booktitle = {Space Telescopes and Instrumentation 2010: Ultraviolet to Gamma Ray},
  editor = {Monique Arnaud and Stephen S. Murray and Tadayuki Takahashi},
  organization = {International Society for Optics and Photonics},
  publisher = {SPIE},
  pages = {197 -- 209},
  keywords = {Hard X-ray telescope, X-ray optics, thermally-slumped glass, NuSTAR},
  year = {2010},
  doi = {},
  URL = {https://doi.org/10.1117/12.857654}
}
  #+end_src

** IAXO

- Towards a new generation axion helioscope
  First paper about IAXO?
  [[file:~/org/Papers/towards_a_new_generation_axion_helioscope_2011_I.G._Irastorza_2011_J._Cosmol._Astropart._Phys._2011_013.pdf]]
  #+begin_src latex :tangle references.bib
@article{Irastorza_2011,
	doi = {10.1088/1475-7516/2011/06/013},
	url = {https://doi.org/10.1088/1475-7516/2011/06/013},
	year = 2011,
	month = {jun},
	publisher = {{IOP} Publishing},
	volume = {2011},
	number = {06},
	pages = {013--013},
	author = {I.G Irastorza and F.T Avignone and S Caspi and J.M Carmona and T Dafni and M Davenport and A Dudarev and G Fanourakis and E Ferrer-Ribas and J Gal{\'{a}}n and J.A Garc{\'{\i}}a and T Geralis and I Giomataris and H G{\'{o}}mez and D.H.H Hoffmann and F.J Iguaz and K Jakov{\v{c}}i{\'{c}} and M Kr{\v{c}}mar and B Laki{\'{c}} and G Luz{\'{o}}n and M Pivovaroff and T Papaevangelou and G Raffelt and J Redondo and A Rodr{\'{\i}}guez and S Russenschuck and J Ruz and I Shilon and H. Ten Kate and A Tom{\'{a}}s and S Troitsky and K. van Bibber and J.A Villar and J Vogel and L Walckiers and K Zioutas},
	title = {Towards a new generation axion helioscope},
	journal = {Journal of Cosmology and Astroparticle Physics}
}  
  #+end_src

- IAXO-the international axion observatory
  First "named" paper about IAXO  
  [[file:~/org/Papers/the_international_axion_observatory_2013_1302.3273.pdf]]
  #+begin_src latex :tangle references.bib
@article{vogel2013iaxo,
  title={IAXO-the international axion observatory},
  author={Vogel, JK and Avignone, FT and Cantatore, G and Carmona, JM and Caspi, S and Cetin, SA and Christensen, FE and Dael, A and Dafni, T and Davenport, M and others},
  journal={arXiv preprint arXiv:1302.3273},
  year={2013}
}  
  #+end_src

- Conceptual design of the International Axion Observatory (IAXO)
  [[file:~/org/Papers/conceptual_design_iaxo_2014_Armengaud_2014_J._Inst._9_T05002.pdf]]
  #+begin_src latex :tangle references.bib
@article{Armengaud_2014,
	doi = {10.1088/1748-0221/9/05/t05002},
	url = {https://doi.org/10.1088/1748-0221/9/05/t05002},
	year = 2014,
	month = {may},
	publisher = {{IOP} Publishing},
	volume = {9},
	number = {05},
	pages = {T05002--T05002},
	author = {E Armengaud and F T Avignone and M Betz and P Brax and P Brun and G Cantatore and J M Carmona and G P Carosi and F Caspers and S Caspi and S A Cetin and D Chelouche and F E Christensen and A Dael and T Dafni and M Davenport and A V Derbin and K Desch and A Diago and B Döbrich and I Dratchnev and A Dudarev and C Eleftheriadis and G Fanourakis and E Ferrer-Ribas and J Gal{\'{a}}n and J A Garc{\'{\i}}a and J G Garza and T Geralis and B Gimeno and I Giomataris and S Gninenko and H G{\'{o}}mez and D Gonz{\'{a}}lez-D{\'{\i}}az and E Guendelman and C J Hailey and T Hiramatsu and D H H Hoffmann and D Horns and F J Iguaz and I G Irastorza and J Isern and K Imai and A C Jakobsen and J Jaeckel and K Jakov{\v{c}}i{\'{c}} and J Kaminski and M Kawasaki and M Karuza and M Kr{\v{c}}mar and K Kousouris and C Krieger and B Laki{\'{c}} and O Limousin and A Lindner and A Liolios and G Luz{\'{o}}n and S Matsuki and V N Muratova and C Nones and I Ortega and T Papaevangelou and M J Pivovaroff and G Raffelt and J Redondo and A Ringwald and S Russenschuck and J Ruz and K Saikawa and I Savvidis and T Sekiguchi and Y K Semertzidis and I Shilon and P Sikivie and H Silva and H ten Kate and A Tomas and S Troitsky and T Vafeiadis and K van Bibber and P Vedrine and J A Villar and J K Vogel and L Walckiers and A Weltman and W Wester and S C Yildiz and K Zioutas},
	title = {Conceptual design of the International Axion Observatory ({IAXO})},
	journal = {Journal of Instrumentation}
}  
  #+end_src

*** BabyIAXO

- Conceptual Design of BabyIAXO, the intermediate stage towards the
  International Axion Observatory
  *The* main thing to cite for BabyIAXO.
  [[file:~/org/Papers/conceptual_design_babyiaxo_2021_Abeln2021_Article_ConceptualDesignOfBabyIAXOTheI.pdf]]
  #+begin_src latex :tangle references.bib
@article{abeln2021conceptual,
  title={Conceptual Design of BabyIAXO, the intermediate stage towards the International Axion Observatory},
  author={Abeln, A and Altenm{\"u}ller, K and Cuendis, S Arguedas and Armengaud, E and Atti{\'e}, D and Aune, S and Basso, S and Berg{\'e}, L and Biasuzzi, B and De Sousa, PTC Borges and others},
  journal={Journal of High Energy Physics},
  volume={2021},
  number={5},
  pages={1--80},
  year={2021},
  publisher={Springer}
}
  #+end_src

** Axion models / primakoff flux
- Weighing the solar axion
  Contains, among others, a plot and (newer) description for the solar axion flux (useful as a comparison)
  Φ_P₁₀ = 6.02e10.cm⁻²•s⁻¹•keV⁻¹
  dΦ_a/dE_a = Φ_P₁₀ (g_aγ / 1e-10.GeV⁻¹) * pow(E_a / 1.keV, 2.481) / (exp(E_a / (1.205.keV)))
  [[file:~/org/Papers/Weighing_the_solar_axion.pdf]]
  https://www.researchgate.net/publication/331334319_Weighing_the_solar_axion
  #+begin_src latex :tangle references.bib
@article{weighingSolarAxion,
  author = {Dafni, Theopisti and O'Hare, Ciaran and Lakić, Biljana and Galan, Javier and Iguaz, F. and Irastorza, Igor and Jakovčić, Krešimir and Luzón, G. and Redondo, Javier and Ruiz-Chóliz, Elisa},
  year = {2019},
  month = {02},
  pages = {},
  title = {Weighing the solar axion},
  volume = {99},
  journal = {Physical Review D},
  doi = {10.1103/PhysRevD.99.035037}
}
#+end_src

** Axion detection  
- Experimental tests of the invisible axion
  1st paper of Sikivie about way to detect axions
  [[file:~/org/Papers/sikivie1983.pdf]]
  #+begin_src latex :tangle references.bib
@article{PhysRevLett.51.1415,
  title = {Experimental Tests of the "Invisible" Axion},
  author = {Sikivie, P.},
  journal = {Phys. Rev. Lett.},
  volume = {51},
  issue = {16},
  pages = {1415--1417},
  numpages = {0},
  year = {1983},
  month = {Oct},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevLett.51.1415},
  url = {https://link.aps.org/doi/10.1103/PhysRevLett.51.1415}
}
  #+end_src

- Detection rates for invisible axion searches, Sikivie
  2nd paper of Sikive about experiments to detect axions.
  [[file:~/org/Papers/sikivie_1985_detection_rates_PhysRevD.32.2988.pdf]]
  #+begin_src latex :tangle references.bib
@article{PhysRevD.32.2988,
  title = {Detection rates for ``invisible''-axion searches},
  author = {Sikivie, P.},
  journal = {Phys. Rev. D},
  volume = {32},
  issue = {11},
  pages = {2988--2991},
  numpages = {0},
  year = {1985},
  month = {Dec},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevD.32.2988},
  url = {https://link.aps.org/doi/10.1103/PhysRevD.32.2988}
}
  #+end_src

- An update on the Axion Helioscopes front: current activities at CAST
  and the IAXO project
  Gives an overview over previous helioscopes!
  [[file:~/org/Papers/update_axion_helioscopes_2016.pdf]]
  #+begin_src latex :tangle references.bib
@article{DAFNI2016244,
  title = {An update on the Axion Helioscopes front: current activities at CAST and the IAXO project},
  journal = {Nuclear and Particle Physics Proceedings},
  volume = {273-275},
  pages = {244-249},
  year = {2016},
  note = {37th International Conference on High Energy Physics (ICHEP)},
  issn = {2405-6014},
  doi = {https://doi.org/10.1016/j.nuclphysbps.2015.09.033},
  url = {https://www.sciencedirect.com/science/article/pii/S2405601415005222},
  author = {T. Dafni and M. Arik and E. Armengaud and S. Aune and F.T. Avignone and K. Barth and A. Belov and M. Betz and H. Bräuninger and P. Brax and N. Breijnholt and P. Brun and G. Cantatore and J.M. Carmona and G.P. Carosi and F. Caspers and S. Caspi and S.A. Cetin and D. Chelouche and F.E. Christensen and J.I. Collar and A. Dael and M. Davenport and A.V. Derbin and K. Desch and A. Diago and B. Döbrich and I. Dratchnev and A. Dudarev and C. Eleftheriadis and G. Fanourakis and E. Ferrer-Ribas and P. Friedrich and J. Galán and J.A. García and A. Gardikiotis and J.G. Garza and E.N. Gazis and E. Georgiopoulou and T. Geralis and B. Gimeno and I. Giomataris and S. Gninenko and H. Gómez and D. González-Díaz and E. Gruber and E. Guendelman and T. Guthörl and C.J. Hailey and R. Hartmann and S. Hauf and F. Haug and M.D. Hasinoff and T. Hiramatsu and D.H.H. Hoffmann and D. Horns and F.J. Iguaz and I.G. Irastorza and J. Isern and K. Imai and J. Jacoby and J. Jaeckel and A.C. Jakobsen and K. Jakovčić and J. Kaminski and M. Kawasaki and M. Karuza and K. Königsmann and R. Kotthaus and M. Krčmar and K. Kousouris and C. Krieger and M. Kuster and B. Lakić and J.M. Laurent and O. Limousin and A. Lindner and A. Liolios and A. Ljubičić and G. Luzón and S. Matsuki and V.N. Muratova and S. Neff and T. Niinikoski and C. Nones and I. Ortega and T. Papaevangelou and M.J. Pivovaroff and G. Raffelt and J. Redondo and H. Riege and A. Ringwald and A. Rodríguez and M. Rosu and S. Russenschuck and J. Ruz and K. Saikawa and I. Savvidis and T. Sekiguchi and Y.K. Semertzidis and I. Shilon and P. Sikivie and H. Silva and S.K. Solanki and L. Stewart and H.H.J. {ten Kate} and A. Tomas and S. Troitsky and T. Vafeiadis and K. {van Bibber} and P. Vedrine and J.A. Villar and J.K. Vogel and L. Walckiers and A. Weltman and W. Wester and S.C. Yildiz and K. Zioutas},
  keywords = {axions, dark matter, x-ray detectors, micromegas detectors, x-ray focusing devices, magnet development, CAST, IAXO}
}  
  #+end_src

** Other axion helioscopes

*** Rochester-Brookhaven-Florida

- Design for a practical laboratory detector for solar axions
  Paper about the first axion helioscope.
  [[file:~/org/Papers/design_practical_lab_detection_solar_axions_brookhaven_PhysRevD.39.2089.pdf]]
#+begin_src latex :tangle references.bib
@article{PhysRevD.39.2089,
  title = {Design for a practical laboratory detector for solar axions},
  author = {van Bibber, K. and McIntyre, P. M. and Morris, D. E. and Raffelt, G. G.},
  journal = {Phys. Rev. D},
  volume = {39},
  issue = {8},
  pages = {2089--2099},
  numpages = {0},
  year = {1989},
  month = {Apr},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevD.39.2089},
  url = {https://link.aps.org/doi/10.1103/PhysRevD.39.2089}
}
#+end_src
- Search for solar axions
  2nd paper about the first axion helioscope
  [[file:~/org/Papers/search_for_solar_axions_brookhaven_PhysRevLett.69.2333.pdf]]
#+begin_src latex :tangle references.bib
@article{PhysRevLett.69.2333,
  title = {Search for solar axions},
  author = {Lazarus, D. M. and Smith, G. C. and Cameron, R. and Melissinos, A. C. and Ruoso, G. and Semertzidis, Y. K. and Nezrick, F. A.},
  journal = {Phys. Rev. Lett.},
  volume = {69},
  issue = {16},
  pages = {2333--2336},
  numpages = {0},
  year = {1992},
  month = {Oct},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevLett.69.2333},
  url = {https://link.aps.org/doi/10.1103/PhysRevLett.69.2333}
}
#+end_src

*** SUMICO

- Direct search for solar axions by using strong magnetic field and
  X-ray detectors
  1st paper about SUMICO.
  [[file:~/org/Papers/sumico_paper_direct_search_for_solar_axions_1998_s0370.pdf]]
  #+begin_src latex :tangle references.bib
@article{MORIYAMA1998147,
  title = {Direct search for solar axions by using strong magnetic field and X-ray detectors},
  journal = {Physics Letters B},
  volume = {434},
  number = {1},
  pages = {147-152},
  year = {1998},
  issn = {0370-2693},
  doi = {https://doi.org/10.1016/S0370-2693(98)00766-7},
  url = {https://www.sciencedirect.com/science/article/pii/S0370269398007667},
  author = {Shigetaka Moriyama and Makoto Minowa and Toshio Namba and Yoshizumi Inoue and Yuko Takasu and Akira Yamamoto},
  keywords = {Axion, Solar core, PIN photodiode, X-ray detector, Superconducting magnet, Nambu-Goldstone boson}
}
  #+end_src

- Search for sub-electronvolt solar axions using coherent conversion
  of axions into photons in magnetic field and gas helium
  2nd paper about SUMICO.
  [[file:~/org/Papers/sumico_2_search_for_sub_ev_solar_axions_2002.pdf]]
  #+begin_src latex :tangle references.bib
@article{INOUE200218,
  title = {Search for sub-electronvolt solar axions using coherent conversion of axions into photons in magnetic field and gas helium},
  journal = {Physics Letters B},
  volume = {536},
  number = {1},
  pages = {18-23},
  year = {2002},
  issn = {0370-2693},
  doi = {https://doi.org/10.1016/S0370-2693(02)01822-1},
  url = {https://www.sciencedirect.com/science/article/pii/S0370269302018221},
  author = {Yoshizumi Inoue and Toshio Namba and Shigetaka Moriyama and Makoto Minowa and Yuko Takasu and Takashi Horiuchi and Akira Yamamoto},
  keywords = {Solar axion, Helioscope, PIN photodiode, Superconducting magnet}
}
  #+end_src

- Search for solar axions with mass around 1 eV using coherent
  conversion of axions into photons
  3rd SUMICO paper.
  [[file:~/org/Papers/sumico_3_search_for_solar_axions_1ev_2008j.physletb.2008.08.020.pdf]]
  #+begin_src latex :tangle references.bib
@article{INOUE200893,
  title = {Search for solar axions with mass around 1 eV using coherent conversion of axions into photons},
  journal = {Physics Letters B},
  volume = {668},
  number = {2},
  pages = {93-97},
  year = {2008},
  issn = {0370-2693},
  doi = {https://doi.org/10.1016/j.physletb.2008.08.020},
  url = {https://www.sciencedirect.com/science/article/pii/S0370269308010137},
  author = {Y. Inoue and Y. Akimoto and R. Ohta and T. Mizumoto and A. Yamamoto and M. Minowa},
  keywords = {Solar axion, Helioscope, PIN photodiode, Superconducting magnet}
}
  #+end_src


** Talks

Igor talk at ICPP 2011:
https://indico.cern.ch/event/117804/contributions/1330107/attachments/58112/83695/Irastorza_ICPP2011.pdf
contains some historic stuff about axion searches


* Detectors

** Gaseous detector physics

- A method to improve tracking and particle identification in TPCs and
  silicon detectors
  Paper that talks about mean vs most probable energy loss from
  Landau, deviation from Landau in energy loss etc. in TPCs
  [[file:~/org/Papers/gaseous_detectors_energy_loss_tpcs_bichsel2006.pdf]]
  #+begin_src latex :tangle references.bib
@article{BICHSEL2006154,
  title = {A method to improve tracking and particle identification in TPCs and silicon detectors},
  journal = {Nuclear Instruments and Methods in Physics Research Section A: Accelerators, Spectrometers, Detectors and Associated Equipment},
  volume = {562},
  number = {1},
  pages = {154-197},
  year = {2006},
  issn = {0168-9002},
  doi = {https://doi.org/10.1016/j.nima.2006.03.009},
  url = {https://www.sciencedirect.com/science/article/pii/S0168900206005353},
  author = {Hans Bichsel},
  keywords = {Energy loss, Ionization, Particle identification, Tracking}
}  
  #+end_src

- 
  Paper that introduced Micromegas. Contains proof (acknowledgments)
  that the name is indeed based on Voltaire!
  https://cds.cern.ch/record/299159/files/SCAN-9603270.pdf


*** Misc

- Slide 15 contains a statement about solving the diffusion / drift
  using the Boltzmann equation exactly:
  https://www.physi.uni-heidelberg.de/~fschney/detektoren/detector3.pdf

  Ref also: https://en.wikipedia.org/wiki/Boltzmann_equation

* General

- PDG
  #+begin_src latex :tangle references.bib
@article{Zyla:2020zbs,
    author = "Zyla, P.A. and others",
    collaboration = "Particle Data Group",
    title = "{Review of Particle Physics}",
    doi = "10.1093/ptep/ptaa104",
    journal = "PTEP",
    volume = "2020",
    number = "8",
    pages = "083C01",
    year = "2020"
}
  #+end_src

- X-ray data booklet
  #+begin_src latex :tangle references.bib
@article{williams2001x,
  title={X-ray data booklet},
  author={Williams, Gwyn P},
  journal={X-ray data booklet},
  url={https://xdb.lbl.gov/xdb-new.pdf},
  year={2001}
}
  #+end_src


* Figures

** Theory

- muon_argon_3cm_bethe_loss
  #+begin_src latex :tangle references.bib
@online{vega_muon_argon_3cm_bethe_loss,
  author = {Vindaar},
  title = {Interactive version of fig. \ref{muon_argon_3cm_bethe_loss}},
  year = {2021},
  url = {https://vega.github.io/editor/#/gist/36357053f61c3838b139a2fca0854a4d/ar_energy_loss_cast.json},
  urldate = {Accessed: 2021-08-17}
}
  #+end_src
