Opening db at /home/basti/CastData/ExternCode/TimepixAnalysis/InGridDatabase/resources/ingridDatabase.h5
Opening db at /home/basti/CastData/ExternCode/TimepixAnalysis/InGridDatabase/resources/ingridDatabase.h5
Opening db at /home/basti/CastData/ExternCode/TimepixAnalysis/InGridDatabase/resources/ingridDatabase.h5
Opening db at /home/basti/CastData/ExternCode/TimepixAnalysis/InGridDatabase/resources/ingridDatabase.h5
Opening db at /home/basti/CastData/ExternCode/TimepixAnalysis/InGridDatabase/resources/ingridDatabase.h5
Opening db at /home/basti/CastData/ExternCode/TimepixAnalysis/InGridDatabase/resources/ingridDatabase.h5
Opening db at /home/basti/CastData/ExternCode/TimepixAnalysis/InGridDatabase/resources/ingridDatabase.h5
Opening db at /home/basti/CastData/ExternCode/TimepixAnalysis/InGridDatabase/resources/ingridDatabase.h5
Opening db at /home/basti/CastData/ExternCode/TimepixAnalysis/InGridDatabase/resources/ingridDatabase.h5
Opening db at /home/basti/CastData/ExternCode/TimepixAnalysis/InGridDatabase/resources/ingridDatabase.h5
Opening db at /home/basti/CastData/ExternCode/TimepixAnalysis/InGridDatabase/resources/ingridDatabase.h5
Opening db at /home/basti/CastData/ExternCode/TimepixAnalysis/InGridDatabase/resources/ingridDatabase.h5
Opening db at /home/basti/CastData/ExternCode/TimepixAnalysis/InGridDatabase/resources/ingridDatabase.h5
Opening db at /home/basti/CastData/ExternCode/TimepixAnalysis/InGridDatabase/resources/ingridDatabase.h5
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 3
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
8 from ticks: 10 from scale: (low: 200.0, high: 600.0) and (low: 200.0, high: 600.0)
8 from ticks: 10 from scale: (low: 200.0, high: 600.0) and (low: 200.0, high: 600.0)
8 from ticks: 10 from scale: (low: 200.0, high: 600.0) and (low: 200.0, high: 600.0)
8 from ticks: 10 from scale: (low: 200.0, high: 600.0) and (low: 200.0, high: 600.0)
8 from ticks: 10 from scale: (low: 200.0, high: 600.0) and (low: 200.0, high: 600.0)
8 from ticks: 10 from scale: (low: 200.0, high: 600.0) and (low: 200.0, high: 600.0)
8 from ticks: 10 from scale: (low: 200.0, high: 600.0) and (low: 200.0, high: 600.0)
8 from ticks: 10 from scale: (low: 200.0, high: 600.0) and (low: 200.0, high: 600.0)
8 from ticks: 10 from scale: (low: 200.0, high: 600.0) and (low: 200.0, high: 600.0)
8 from ticks: 10 from scale: (low: 200.0, high: 600.0) and (low: 200.0, high: 600.0)
8 from ticks: 10 from scale: (low: 200.0, high: 600.0) and (low: 200.0, high: 600.0)
8 from ticks: 10 from scale: (low: 200.0, high: 600.0) and (low: 200.0, high: 600.0)
8 from ticks: 10 from scale: (low: 200.0, high: 600.0) and (low: 200.0, high: 600.0)
8 from ticks: 10 from scale: (low: 200.0, high: 600.0) and (low: 200.0, high: 600.0)
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
6 from ticks: 10 from scale: (low: 0.0, high: 6000.0) and (low: 0.0, high: 6000.0)
7 from ticks: 10 from scale: (low: 0.0, high: 7000.0) and (low: 0.0, high: 7000.0)
6 from ticks: 10 from scale: (low: 0.0, high: 6000.0) and (low: 0.0, high: 6000.0)
6 from ticks: 10 from scale: (low: 0.0, high: 6000.0) and (low: 0.0, high: 6000.0)
7 from ticks: 10 from scale: (low: 0.0, high: 7000.0) and (low: 0.0, high: 7000.0)
6 from ticks: 10 from scale: (low: 0.0, high: 6000.0) and (low: 0.0, high: 6000.0)
6 from ticks: 10 from scale: (low: 0.0, high: 6000.0) and (low: 0.0, high: 6000.0)
6 from ticks: 10 from scale: (low: 0.0, high: 6000.0) and (low: 0.0, high: 6000.0)
6 from ticks: 10 from scale: (low: 0.0, high: 6000.0) and (low: 0.0, high: 6000.0)
6 from ticks: 10 from scale: (low: 0.0, high: 6000.0) and (low: 0.0, high: 6000.0)
6 from ticks: 10 from scale: (low: 0.0, high: 6000.0) and (low: 0.0, high: 6000.0)
6 from ticks: 10 from scale: (low: 0.0, high: 6000.0) and (low: 0.0, high: 6000.0)
7 from ticks: 10 from scale: (low: 0.0, high: 7000.0) and (low: 0.0, high: 7000.0)
6 from ticks: 10 from scale: (low: 0.0, high: 6000.0) and (low: 0.0, high: 6000.0)
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/s_curves_0_Run3_lX_200.0_lY_3750.0.tex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/s_curves_4_Run3_lX_200.0_lY_3750.0.tex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/s_curves_0_Run2_lX_200.0_lY_3750.0.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/s_curves_1_Run3_lX_200.0_lY_3750.0.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/s_curves_4_Run2_lX_200.0_lY_3750.0.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/s_curves_2_Run3_lX_200.0_lY_3750.0.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/s_curves_3_Run2_lX_200.0_lY_3750.0.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/s_curves_5_Run3_lX_200.0_lY_3750.0.tex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/s_curves_5_Run2_lX_200.0_lY_3750.0.tex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/s_curves_6_Run3_lX_200.0_lY_3750.0.tex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/s_curves_6_Run2_lX_200.0_lY_3750.0.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/s_curves_1_Run2_lX_200.0_lY_3750.0.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/s_curves_2_Run2_lX_200.0_lY_3750.0.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/s_curves_3_Run3_lX_200.0_lY_3750.0.tex
Generated: /home/basti/phd/Figs/detector/calibration/s_curves_4_Run3_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/s_curves_3_Run2_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/s_curves_4_Run2_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/s_curves_1_Run3_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/s_curves_5_Run3_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/s_curves_0_Run3_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/s_curves_2_Run2_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/s_curves_0_Run2_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/s_curves_6_Run2_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/s_curves_5_Run2_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/s_curves_2_Run3_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/s_curves_3_Run3_lX_200.0_lY_3750.0.pdf
| chip | voltage | runPeriod | N | ΔN | μ | Δμ | σ | Δσ |
|----|----|----|----|----|----|----|----|----|
|4|20|Run3|999.7|0.4|437.3|0.004919|4.256|0.006459|
|4|25|Run3|1003|0.376|446.7|0.005023|4.561|0.006614|
|4|30|Run3|999.5|0.3509|455.5|0.004807|4.4|0.006384|
|4|35|Run3|999.4|0.424|465.1|0.005229|4.494|0.0068|
|4|40|Run3|997.6|0.372|474.8|0.004981|4.492|0.006571|
|4|50|Run3|997.6|0.4397|492.6|0.005304|4.476|0.006868|
|4|60|Run3|1004|0.3632|511.5|0.005063|4.706|0.006681|
|4|100|Run3|998.8|0.3903|582.7|0.005315|4.818|0.00695|

*** testlinfit status = 1
9 from ticks: 10 from scale: (low: 420.0, high: 600.0) and (low: 420.0, high: 600.0)
| chip | voltage | runPeriod | N | ΔN | μ | Δμ | σ | Δσ |
|----|----|----|----|----|----|----|----|----|
|3|20|Run2|1020|1.225|422.9|0.00906|4.107|0.009371|
|3|25|Run2|1011|0.5655|428.1|0.005788|4.353|0.007229|
|3|30|Run2|1003|0.3785|433.1|0.004842|4.303|0.006391|
|3|35|Run2|1001|0.3727|438.4|0.004825|4.305|0.006377|
|3|40|Run2|1001|0.3724|444.3|0.004802|4.272|0.00635|
|3|50|Run2|1001|0.3643|454.1|0.004931|4.496|0.006519|
|3|60|Run2|999.5|0.3824|464.3|0.005009|4.477|0.006591|
|3|100|Run2|1005|0.4337|502.6|0.005988|5.397|0.007674|

*** testlinfit status = 1
9 from ticks: 10 from scale: (low: 420.0, high: 510.0) and (low: 420.0, high: 510.0)
| chip | voltage | runPeriod | N | ΔN | μ | Δμ | σ | Δσ |
|----|----|----|----|----|----|----|----|----|
|4|20|Run2|1040|1.203|427.4|0.009416|4.453|0.009669|
|4|25|Run2|1006|0.6367|433.2|0.006145|4.298|0.007513|
|4|30|Run2|1005|0.3829|438.1|0.004901|4.371|0.006456|
|4|35|Run2|1001|0.3561|443.3|0.004829|4.407|0.006405|
|4|40|Run2|1001|0.4318|449.2|0.005384|4.642|0.006972|
|4|50|Run2|999.3|0.362|459.1|0.004891|4.445|0.006473|
|4|60|Run2|1010|0.4457|469.4|0.005662|4.944|0.00727|
|4|100|Run2|1006|0.4092|507.6|0.005949|5.552|0.00768|

*** testlinfit status = 3
9 from ticks: 10 from scale: (low: 420.0, high: 510.0) and (low: 420.0, high: 510.0)
Generated: /home/basti/phd/Figs/detector/calibration/s_curves_6_Run3_lX_200.0_lY_3750.0.pdf
| chip | voltage | runPeriod | N | ΔN | μ | Δμ | σ | Δσ |
|----|----|----|----|----|----|----|----|----|
|1|20|Run3|1007|0.5532|384.6|0.00592|4.532|0.007397|
|1|25|Run3|1023|0.6033|393.6|0.007034|5.418|0.008488|
|1|30|Run3|1000|0.467|403.7|0.005764|4.853|0.007362|
|1|35|Run3|983.4|0.3714|413.1|0.004776|4.133|0.006327|
|1|40|Run3|1013|0.3916|422|0.005359|4.966|0.006994|
|1|50|Run3|1022|0.6807|440.9|0.007737|5.551|0.009052|
|1|60|Run3|982.4|0.3855|461.3|0.005151|4.526|0.006767|
|1|100|Run3|999.6|0.3774|534.6|0.005401|5.032|0.007076|

*** testlinfit status = 3
8 from ticks: 10 from scale: (low: 380.0, high: 540.0) and (low: 380.0, high: 540.0)
| chip | voltage | runPeriod | N | ΔN | μ | Δμ | σ | Δσ |
|----|----|----|----|----|----|----|----|----|
|5|20|Run3|980.6|0.3185|351.3|0.004076|3.441|0.005511|
|5|25|Run3|1012|0.4223|359.8|0.005834|5.346|0.007509|
|5|30|Run3|1003|0.3553|369.1|0.00509|4.786|0.006727|
|5|35|Run3|999.5|0.5331|378.9|0.006367|5.063|0.007928|
|5|40|Run3|991.5|0.4121|388.8|0.005378|4.701|0.006998|
|5|50|Run3|993.7|0.3681|406.8|0.004946|4.445|0.006536|
|5|60|Run3|1009|0.3795|425.5|0.005705|5.503|0.007451|
|5|100|Run3|1006|0.4792|498.9|0.006008|5.086|0.007616|

*** testlinfit status = 3
8 from ticks: 10 from scale: (low: 340.0, high: 500.0) and (low: 340.0, high: 500.0)
Generated: /home/basti/phd/Figs/detector/calibration/s_curves_1_Run2_lX_200.0_lY_3750.0.pdf
| chip | voltage | runPeriod | N | ΔN | μ | Δμ | σ | Δσ |
|----|----|----|----|----|----|----|----|----|
|0|20|Run3|1001|0.37|421.3|0.004754|4.221|0.006294|
|0|25|Run3|1004|0.3732|430.8|0.004994|4.545|0.006582|
|0|30|Run3|1000|0.3867|440.1|0.004989|4.429|0.006561|
|0|35|Run3|1005|0.3935|449.3|0.005154|4.627|0.006748|
|0|40|Run3|1002|0.3842|459.4|0.005048|4.53|0.006635|
|0|50|Run3|1002|0.3928|478.2|0.005145|4.603|0.006741|
|0|60|Run3|1001|0.3806|497.6|0.00505|4.553|0.006643|
|0|100|Run3|1004|0.3936|569.8|0.005365|4.895|0.007004|

*** testlinfit status = 1
8 from ticks: 10 from scale: (low: 420.0, high: 580.0) and (low: 420.0, high: 580.0)
| chip | voltage | runPeriod | N | ΔN | μ | Δμ | σ | Δσ |
|----|----|----|----|----|----|----|----|----|
|2|20|Run2|998.4|0.8093|351.8|0.007102|4.242|0.008231|
|2|25|Run2|1028|0.7173|356.9|0.006721|4.518|0.00796|
|2|30|Run2|1006|0.396|362.3|0.005205|4.683|0.006806|
|2|35|Run2|1003|0.3835|368.1|0.005318|4.898|0.006962|
|2|40|Run2|1013|0.4821|373.9|0.006488|5.664|0.008148|
|2|50|Run2|985.4|0.405|386.9|0.005722|5.14|0.007423|
|2|60|Run2|1015|0.4928|397.8|0.006599|5.721|0.008248|
|2|100|Run2|1002|0.4138|436|0.005847|5.353|0.007547|

*** testlinfit status = 1
| chip | voltage | runPeriod | N | ΔN | μ | Δμ | σ | Δσ |
|----|----|----|----|----|----|----|----|----|
|6|20|Run2|1008|1.057|400.5|0.00954|4.876|0.01006|
|6|25|Run2|981.7|0.433|407.7|0.005316|4.43|0.006901|
|6|30|Run2|990.9|0.3359|413.2|0.004408|3.878|0.005909|
|6|35|Run2|996.6|0.3557|417.6|0.004588|4.055|0.006108|
|6|40|Run2|995.3|0.3669|423.4|0.004743|4.192|0.006287|
|6|50|Run2|995.7|0.384|433.3|0.005026|4.464|0.006612|
|6|60|Run2|990.4|0.3798|444.6|0.005093|4.542|0.006701|
|6|100|Run2|998.2|0.4102|483.5|0.00559|5.026|0.007249|

*** testlinfit status = 1
10 from ticks: 10 from scale: (low: 390.0, high: 490.0) and (low: 390.0, high: 490.0)
9 from ticks: 10 from scale: (low: 350.0, high: 440.0) and (low: 350.0, high: 440.0)
| chip | voltage | runPeriod | N | ΔN | μ | Δμ | σ | Δσ |
|----|----|----|----|----|----|----|----|----|
|2|20|Run3|1000|0.3853|366.4|0.005084|4.56|0.006677|
|2|25|Run3|1001|0.3791|375.9|0.005146|4.689|0.006762|
|2|30|Run3|1003|0.4448|384.9|0.005457|4.657|0.007037|
|2|35|Run3|1001|0.3878|394.5|0.005168|4.66|0.006776|
|2|40|Run3|1001|0.4325|405|0.005309|4.55|0.006881|
|2|50|Run3|1002|0.3695|423.3|0.005096|4.69|0.006713|
|2|60|Run3|1001|0.3829|443.1|0.005312|4.886|0.006957|
|2|100|Run3|1003|0.3783|516.5|0.005342|4.972|0.007|

*** testlinfit status = 3
8 from ticks: 10 from scale: (low: 360.0, high: 520.0) and (low: 360.0, high: 520.0)
| chip | voltage | runPeriod | N | ΔN | μ | Δμ | σ | Δσ |
|----|----|----|----|----|----|----|----|----|
|3|20|Run3|998.8|0.3833|436|0.004918|4.348|0.006479|
|3|25|Run3|1002|0.377|445.6|0.005006|4.521|0.006593|
|3|30|Run3|1001|0.3666|454.1|0.00497|4.537|0.006564|
|3|35|Run3|1005|0.3822|463.6|0.005077|4.604|0.00667|
|3|40|Run3|1001|0.3767|473.6|0.004984|4.488|0.006567|
|3|50|Run3|1002|0.3772|491.7|0.005049|4.579|0.006646|
|3|60|Run3|999.8|0.3738|511.6|0.00493|4.427|0.006506|
|3|100|Run3|954.5|0.3897|583.8|0.005565|4.828|0.007279|

*** testlinfit status = 1
[INFO] TeXDaemon ready for input.
9 from ticks: 10 from scale: (low: 420.0, high: 600.0) and (low: 420.0, high: 600.0)
| chip | voltage | runPeriod | N | ΔN | μ | Δμ | σ | Δσ |
|----|----|----|----|----|----|----|----|----|
|0|20|Run2|989.8|0.8928|408.9|0.007268|3.991|0.008277|
|0|25|Run2|1006|0.4597|414.2|0.004923|3.974|0.006386|
|0|30|Run2|1004|0.3651|419.2|0.004602|4.067|0.006111|
|0|35|Run2|999.3|0.3604|424.4|0.004597|4.058|0.006113|
|0|40|Run2|1003|0.3845|429.2|0.004994|4.465|0.006569|
|0|50|Run2|1002|0.3689|439|0.00499|4.554|0.006585|
|0|60|Run2|1004|0.4107|449.1|0.00541|4.834|0.007032|
|0|100|Run2|1013|0.4559|486.9|0.006465|5.853|0.008183|

*** testlinfit status = 1
| chip | voltage | runPeriod | N | ΔN | μ | Δμ | σ | Δσ |
|----|----|----|----|----|----|----|----|----|
|5|20|Run2|1017|0.9365|336|0.007614|4.191|0.008502|
|5|25|Run2|1047|0.7914|341.5|0.00795|5.237|0.009016|
|5|30|Run2|988|0.4721|347.8|0.005962|4.962|0.007589|
|5|35|Run2|993.4|0.3367|352.5|0.004536|4.066|0.006067|
|5|40|Run2|1002|0.3981|357.8|0.005052|4.453|0.00662|
|5|50|Run2|999|0.3784|368.3|0.005305|4.891|0.006957|
|5|60|Run2|982.6|0.4703|381.5|0.006751|5.831|0.0085|
|5|100|Run2|1009|0.407|420.7|0.005546|5.066|0.007196|

*** testlinfit status = 1
9 from ticks: 10 from scale: (low: 400.0, high: 490.0) and (low: 400.0, high: 490.0)
10 from ticks: 10 from scale: (low: 330.0, high: 430.0) and (low: 330.0, high: 430.0)
| chip | voltage | runPeriod | N | ΔN | μ | Δμ | σ | Δσ |
|----|----|----|----|----|----|----|----|----|
|6|20|Run3|993.9|0.375|413.2|0.004854|4.282|0.006414|
|6|25|Run3|1002|0.3873|422.3|0.005074|4.549|0.006662|
|6|30|Run3|997.5|0.3923|431.5|0.005272|4.74|0.006896|
|6|35|Run3|1000|0.4067|441.1|0.005354|4.764|0.006972|
|6|40|Run3|1001|0.379|450.8|0.005124|4.662|0.006734|
|6|50|Run3|1005|0.4097|469.4|0.005494|4.956|0.007131|
|6|60|Run3|1000|0.3918|489.3|0.005174|4.637|0.006778|
|6|100|Run3|1009|0.4163|562.9|0.005794|5.32|0.007475|

*** testlinfit status = 2
9 from ticks: 10 from scale: (low: 400.0, high: 580.0) and (low: 400.0, high: 580.0)
[INFO] TeXDaemon ready for input.
| chip | voltage | runPeriod | N | ΔN | μ | Δμ | σ | Δσ |
|----|----|----|----|----|----|----|----|----|
|1|20|Run2|1069|1.481|368.1|0.01156|4.832|0.01095|
|1|25|Run2|1067|0.7955|374.7|0.009635|6.7|0.01062|
|1|30|Run2|975.2|0.3802|382.1|0.005377|4.803|0.007053|
|1|35|Run2|990.6|0.4188|387.6|0.005426|4.709|0.007046|
|1|40|Run2|1023|0.6093|393.5|0.007115|5.453|0.008561|
|1|50|Run2|989.8|0.4391|405.3|0.006054|5.321|0.007752|
|1|60|Run2|987.7|0.3325|415.5|0.004108|3.466|0.005535|
|1|100|Run2|1018|0.4941|452.2|0.006787|5.945|0.008457|

*** testlinfit status = 1
10 from ticks: 10 from scale: (low: 360.0, high: 460.0) and (low: 360.0, high: 460.0)
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
9 from ticks: 10 from scale: (low: 500.0, high: 5000.0) and (low: 500.0, high: 5000.0)
9 from ticks: 10 from scale: (low: 500.0, high: 5000.0) and (low: 500.0, high: 5000.0)
9 from ticks: 10 from scale: (low: 500.0, high: 5000.0) and (low: 500.0, high: 5000.0)
shellCmd: command -v lualatex
9 from ticks: 10 from scale: (low: 500.0, high: 5000.0) and (low: 500.0, high: 5000.0)
9 from ticks: 10 from scale: (low: 500.0, high: 5000.0) and (low: 500.0, high: 5000.0)
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_4_Run3_lX_200.0_lY_3750.0.tex
shellCmd: command -v lualatex
9 from ticks: 10 from scale: (low: 500.0, high: 5000.0) and (low: 500.0, high: 5000.0)
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_3_Run2_lX_200.0_lY_3750.0.tex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
9 from ticks: 10 from scale: (low: 500.0, high: 5000.0) and (low: 500.0, high: 5000.0)
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_4_Run2_lX_200.0_lY_3750.0.tex
9 from ticks: 10 from scale: (low: 500.0, high: 5000.0) and (low: 500.0, high: 5000.0)
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_1_Run3_lX_200.0_lY_3750.0.tex
9 from ticks: 10 from scale: (low: 500.0, high: 5000.0) and (low: 500.0, high: 5000.0)
9 from ticks: 10 from scale: (low: 500.0, high: 5000.0) and (low: 500.0, high: 5000.0)
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_5_Run3_lX_200.0_lY_3750.0.tex
shellCmd: command -v lualatex
9 from ticks: 10 from scale: (low: 500.0, high: 5000.0) and (low: 500.0, high: 5000.0)
9 from ticks: 10 from scale: (low: 500.0, high: 5000.0) and (low: 500.0, high: 5000.0)
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_0_Run3_lX_200.0_lY_3750.0.tex
9 from ticks: 10 from scale: (low: 500.0, high: 5000.0) and (low: 500.0, high: 5000.0)
9 from ticks: 10 from scale: (low: 500.0, high: 5000.0) and (low: 500.0, high: 5000.0)
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_6_Run2_lX_200.0_lY_3750.0.tex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_3_Run3_lX_200.0_lY_3750.0.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_2_Run3_lX_200.0_lY_3750.0.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_0_Run2_lX_200.0_lY_3750.0.tex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_2_Run2_lX_200.0_lY_3750.0.tex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_5_Run2_lX_200.0_lY_3750.0.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_6_Run3_lX_200.0_lY_3750.0.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_1_Run2_lX_200.0_lY_3750.0.tex
Generated: /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_4_Run3_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_5_Run3_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_3_Run2_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_1_Run3_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_4_Run2_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_0_Run3_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_3_Run3_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_6_Run2_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_0_Run2_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_5_Run2_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_2_Run3_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_2_Run2_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_6_Run3_lX_200.0_lY_3750.0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/thl_calibration_chip_1_Run2_lX_200.0_lY_3750.0.pdf
