*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
*** testlinfit status = 1
9 from ticks: 10 from scale: (low: 0.0, high: 450.0) and (low: 0.0, high: 450.0)
8 from ticks: 10 from scale: (low: 50.0, high: 450.0) and (low: 50.0, high: 450.0)
9 from ticks: 10 from scale: (low: 0.0, high: 450.0) and (low: 0.0, high: 450.0)
*** testlinfit status = 1
9 from ticks: 10 from scale: (low: 0.0, high: 450.0) and (low: 0.0, high: 450.0)
*** testlinfit status = 1
9 from ticks: 10 from scale: (low: 0.0, high: 450.0) and (low: 0.0, high: 450.0)
*** testlinfit status = 1
*** testlinfit status = 1
9 from ticks: 10 from scale: (low: 0.0, high: 450.0) and (low: 0.0, high: 450.0)
*** testlinfit status = 1
9 from ticks: 10 from scale: (low: 0.0, high: 450.0) and (low: 0.0, high: 450.0)
9 from ticks: 10 from scale: (low: 0.0, high: 450.0) and (low: 0.0, high: 450.0)
*** testlinfit status = 5
9 from ticks: 10 from scale: (low: 0.0, high: 450.0) and (low: 0.0, high: 450.0)
*** testlinfit status = 1
*** testlinfit status = 1
9 from ticks: 10 from scale: (low: 0.0, high: 450.0) and (low: 0.0, high: 450.0)
9 from ticks: 10 from scale: (low: 0.0, high: 450.0) and (low: 0.0, high: 450.0)
9 from ticks: 10 from scale: (low: 0.0, high: 450.0) and (low: 0.0, high: 450.0)
9 from ticks: 10 from scale: (low: 0.0, high: 450.0) and (low: 0.0, high: 450.0)
9 from ticks: 10 from scale: (low: 0.0, high: 450.0) and (low: 0.0, high: 450.0)
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
[INFO] TeXDaemon ready for input.
5 from ticks: 10 from scale: (low: 0.0, high: 250.0) and (low: 0.0, high: 250.0)
5 from ticks: 10 from scale: (low: 0.0, high: 250.0) and (low: 0.0, high: 250.0)
5 from ticks: 10 from scale: (low: 0.0, high: 250.0) and (low: 0.0, high: 250.0)
5 from ticks: 10 from scale: (low: 0.0, high: 250.0) and (low: 0.0, high: 250.0)
5 from ticks: 10 from scale: (low: 0.0, high: 250.0) and (low: 0.0, high: 250.0)
5 from ticks: 10 from scale: (low: 0.0, high: 250.0) and (low: 0.0, high: 250.0)
5 from ticks: 10 from scale: (low: 0.0, high: 250.0) and (low: 0.0, high: 250.0)
5 from ticks: 10 from scale: (low: 0.0, high: 250.0) and (low: 0.0, high: 250.0)
5 from ticks: 10 from scale: (low: 0.0, high: 250.0) and (low: 0.0, high: 250.0)
5 from ticks: 10 from scale: (low: 0.0, high: 250.0) and (low: 0.0, high: 250.0)
5 from ticks: 10 from scale: (low: 0.0, high: 250.0) and (low: 0.0, high: 250.0)
5 from ticks: 10 from scale: (low: 0.0, high: 250.0) and (low: 0.0, high: 250.0)
5 from ticks: 10 from scale: (low: 0.0, high: 250.0) and (low: 0.0, high: 250.0)
5 from ticks: 10 from scale: (low: 0.0, high: 250.0) and (low: 0.0, high: 250.0)
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/tot_calib_Run2_chip_2.tex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/tot_calib_Run3_chip_3.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/tot_calib_Run2_chip_3.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/tot_calib_Run3_chip_1.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/tot_calib_Run2_chip_0.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/tot_calib_Run3_chip_6.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/tot_calib_Run3_chip_2.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/tot_calib_Run2_chip_4.tex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/tot_calib_Run3_chip_4.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/tot_calib_Run2_chip_1.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/tot_calib_Run2_chip_5.tex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/tot_calib_Run3_chip_5.tex
shellCmd: command -v lualatex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/tot_calib_Run3_chip_0.tex
shellCmd: lualatex -output-directory /home/basti/phd/Figs/detector/calibration /home/basti/phd/Figs/detector/calibration/tot_calib_Run2_chip_6.tex
Generated: /home/basti/phd/Figs/detector/calibration/tot_calib_Run2_chip_2.pdf
Generated: /home/basti/phd/Figs/detector/calibration/tot_calib_Run2_chip_3.pdf
Generated: /home/basti/phd/Figs/detector/calibration/tot_calib_Run3_chip_3.pdf
Generated: /home/basti/phd/Figs/detector/calibration/tot_calib_Run3_chip_1.pdf
Generated: /home/basti/phd/Figs/detector/calibration/tot_calib_Run3_chip_2.pdf
Generated: /home/basti/phd/Figs/detector/calibration/tot_calib_Run2_chip_5.pdf
Generated: /home/basti/phd/Figs/detector/calibration/tot_calib_Run3_chip_5.pdf
Generated: /home/basti/phd/Figs/detector/calibration/tot_calib_Run2_chip_4.pdf
Generated: /home/basti/phd/Figs/detector/calibration/tot_calib_Run3_chip_6.pdf
Generated: /home/basti/phd/Figs/detector/calibration/tot_calib_Run3_chip_4.pdf
Generated: /home/basti/phd/Figs/detector/calibration/tot_calib_Run2_chip_1.pdf
Generated: /home/basti/phd/Figs/detector/calibration/tot_calib_Run2_chip_6.pdf
Generated: /home/basti/phd/Figs/detector/calibration/tot_calib_Run3_chip_0.pdf
Generated: /home/basti/phd/Figs/detector/calibration/tot_calib_Run2_chip_0.pdf
