#+SETUPFILE: ~/.emacs.d/default_latex_header.org

# Better use my full name as author for this!
#+AUTHOR: Sebastian Schmidt

#+OPTIONS: html-style:nil

* Search for solar axions using a 7-GridPix IAXO prototype detector at CAST

This is the companion website to my PhD thesis of the above title. At
the time of writing this, <2024-01-18 Thu 18:49>, it does not yet link
to the entire thesis document. That will only be done once the thesis
has been defended and published (it seems like otherwise I might get
into trouble).

If you want access to the extended version of the thesis beforehand,
please just get in touch by mail via phd@vindaar.de.

** Errata (print version)                                                         

This is a list of known issues in the printed version that I handed
in. The box indicates whether these have been fixed.

- [ ] <2024-02-01 Thu 18:26> The background rate plots, over the
  entire chip, which use ~filterNoisyPixels~ use the list of pixels
  from the Timepix3 detector and not the small noise region for the
  Septemboard. That implies the background rates might be a small bit
  higher in the full chip background rate plots than in reality.
- [ ] The appendix about the software and how to reconstruct the
  entire results, still lists the data reference as XXX instead of the
  correct link.
- [X] The text below the figure explaining the FADC as a means to
  close the Timepix shutter mentions a time difference of 50μs. I
  think that should be 50 clock cycles. Need to cross check.
  -> Update <2024-02-07 Wed 11:34>. Indeed, the time should have been
  5 μs and 200 clock cycles. See [[file:~/org/journal.org::#sec:journal:07_02_24:fadc_shutter_close]]
  and this definition here:
  [[file:~/CastData/ExternCode/TOS/include/fpga.hpp::49]]
  https://github.com/Vindaar/TOS/blob/master/include/fpga.hpp#L49-L51
  (which is used in the ~fpga~ constructor and set in
  ~EnableFADCShutter~ without being changed).

** Abstract

The Standard Model of particle physics (SM) is extremely successful at
describing three out of the four known fundamental forces of
nature. However, there are several open questions even within the
SM. One of those is termed the 'strong CP problem'. In a simplified
way it asks why the neutron does not have an electric dipole
moment. While only a mathematical problem of sorts, it can be neatly
solved by the introduction of a new hypothetical particle, the
/axion/. This particle can interact with photons and leptons, even if
extremely feebly. If they exist, they will be produced in the 
core of the Sun at very high rates, but easily escape similar to
neutrinos. On the Earth we can attempt to detect them using strong
magnetic fields. The latest such experiment, a solar helioscope, is
the CERN Axion Solar Telescope (CAST). Axions carry the energy of the
photons, which initially produced them, placing them in the soft X-ray
energy range.

In the course of this thesis, a gaseous detector using 7-GridPixes as
its readout was deployed at the CAST experiment in 2017/18 to follow
up on previous measurements with a single GridPix detector in
2014/15. $\SI{3150}{h}$ of background data and $\SI{160}{h}$ of solar
tracking data was taken. The data taken at such an experiment is
dominated by cosmic radiation, radioactive background and X-ray
fluorescence. As such methods to suppress this background and extract
the few possible axion signals are needed. A software library
~TimepixAnalysis~ was developed in the course of this thesis to
reconstruct and analyze the data taken at CAST.

For the classification of event data into background-like or
signal-like (X-ray) data, a machine learning approach is used. A
multilayer perceptron (MLP, simple type of an artificial neural
network) was trained on synthetic X-ray data and CAST background data
of 6 of the 7 chips (leaving out the chip sensitive to axions). This
method significantly improves the signal efficiency at comparable
background rates, when compared to the likelihood cut method used for
the old detector.

Further, as no excess signal was detected in the solar tracking
dataset, a limit calculation method was developed. This method builds on the
unbinned Bayesian likelihood method used in CAST's Nature paper
in 2017. It is extended to allow the inclusion of systematic
uncertainties as nuisance parameters. Due to the very expensive
evaluation of such a likelihood function, a Markov Chain Monte Carlo
(MCMC) approach is used.

One of the limit calculation inputs is the 'axion image' produced by
the Lawrence Livermore National Laboratory (LLNL) telescope at
CAST. To properly characterize this, a raytracing simulation taking
into account the axion production rates in the Sun and reflection
through the X-ray optic was developed. It was verified against
PANTER measurements of the telescope.

With the software advances and improved detector features, world best
limits could be set on the axion-electron coupling and on the
chameleon coupling (a separate hypothetical particle). The previous
best limit on the axion-electron coupling is improved from
$g_{ae}·g_{aγ} \lesssim \SI{8.1e-23}{GeV⁻¹}$ to $g_{ae}·g_{aγ}
\lesssim \SI{7.35e-23}{GeV⁻¹}$ and the chameleon coupling from $β_γ <
\num{5.74e10}$ to $β_γ \lesssim \num{3.1e+10}$.

In addition, the software developed during the course of this thesis
was written with future detectors in mind. It is in principle ready
for data analysis for a GridPix3 based future detector.

** Data

One of the most important parts for my thesis has always been being
able to replicate results. Part of that is providing access to my
data, including the raw data taken with our detector at CAST.

Due to some technical issues with [[https://zenodo.org][Zenodo]] I haven't been able to
successfully upload my data to their servers so far (the connection is
closed before the upload finishes).

For that reason, for the time being until I manage this, you can find
the entire raw dataset under this Google Drive link:

https://drive.google.com/file/d/1o57wgDeVW82BmL_lHH-ZRm5zHXRWWVYI/view?usp=drive_link

(I hope I don't regret this :) )

** Software

The main repository used in my thesis is [[https://github.com/Vindaar/TimepixAnalysis][TimepixAnalysis]]. See the
appendix about the software and how to reconstruct all data in the
thesis for more information.

The results in the thesis were all produced with the git tag ~phd_rc0~
(at the time of writing, I still have to finalize the git tags for
~datamancer~, ~ggplotnim~, ~unchained~, ~nimhdf5~ and maybe a couple
more libraries that I've tinkered with in the final days of
writing). Once the final thesis is published I'll create a ~phd~ tag
(and make sure I didn't break anything in between).

** Additional notes and information

There are 2 major files potentially of interest to the kind of reader
who may stumble on this website.

The first is a sort-of journal I wrote over the years. It was used
more as a day-to-day journal in 2023 and contains some other
'journaley' notes from before.

The second is my "status and progress" type document. It contains a
large amount of notes related to all sorts of researching ideas /
results etc. Almost all things that ended up in the thesis were
written at one point or another in one of the two documents. So they
may be worthwhile to look into.

- The 'journal':
  http://files.vindaar.de/journal/journal.html
- The status and progress notes:
  http://files.vindaar.de/status/StatusAndProgress.html

Note that both of these documents are very large. At least on my
laptop running Brave these two pages are no fun. Firefox however deals
with them very well. I'll probably end up splitting them into
different pages at some point. But if you are more seriously
interested in them, I recommend downloading the Org file of the
document (just replace the ~.html~ ending by ~.org~; note: currently
not available for the ~journal~, because I use that journal for stuff
unrelated to the PhD as well and I haven't produced a standalone Org
file without those...).

Aside from these, another 2 files may be of interest:
- The calculations related to a possible gas phase for (Baby)IAXO:
  http://files.vindaar.de/phd/docs/bufferGasIAXO/v1/axionMass.html
  or
  http://files.vindaar.de/phd/docs/bufferGasIAXO/v1/index.html
- The original document of the notes containing the calculation of the
  median and mean conversion point of axions from the Sun in our detector:
  http://files.vindaar.de/phd/docs/SolarAxionConversionPoint/axion_conversion_point.html  
  These are almost identical to the appendix about the same in the thesis.

A few other documents exist that I might upload at some other time
(related to the LLNL telescope, raytracing etc.). These are mostly
already contained in some form or another in the above though. 

** Note about TLS

The website is currently just files publicly linked on Backblaze
B2. I might migrate them elsewhere (maybe just github pages for the
time being?) to somewhere where TLS is easy to setup.

But then again, who cares for this kind of stuff?
